# Generated by /feature-spec
# Feature: Flutter tap-to-talk voice client (FEAT-VOICE-003)
# Stack: dart (Flutter client under app/; the root repo auto-detects as python)
# Assumptions: 11 (see flutter-voice-client_assumptions.yaml)
# Generated: 2026-07-07T08:04:13+01:00
#
# Companion features: FEAT-VOICE-001 (voice-server-module) owns the server-side
# upload-validation rulebook and its boundary pairs; FEAT-VOICE-002 (streaming-voice)
# owns the server streaming path, WS frame ordering, and chunk-by-URL delivery. This
# spec covers only the Flutter CLIENT's observable behaviour and deliberately does not
# duplicate them.
#
# [ASSUMPTION: confidence=high] Voice adds exactly three runtime dependencies — record,
# just_audio, web_socket_channel — and no state-management package; this is the
# deliberate amendment of the app's zero-added-deps DoD (design §6.1), recorded here as
# a conscious scope event.

@voice @feat-voice-003
Feature: Flutter tap-to-talk voice client
  As a student using the tutor on my phone
  I want to ask questions by speaking and hear the answer spoken back
  So that I can learn hands-free without typing

  Background:
    Given I am signed in and in an active tutoring session on my phone

  # ── Key examples ──────────────────────────────────────────────────────

  # Why: The core tap-to-talk loop — speak, see it recognised, hear the answer (MVP path)
  @task:TASK-VC-005
  @key-example @smoke
  Scenario: Asking a question by voice and hearing the tutor's spoken answer
    Given I am in a tutoring session on my phone
    When I press the mic button, speak a question, and press again to send
    Then the transcript of my question appears in the session like a typed question
    And the tutor's answer appears and is spoken aloud

  # Why: The transcript is the user-visible confirmation the tutor heard correctly — it comes first
  @task:TASK-VC-005
  @key-example
  Scenario: My spoken question is shown as text before the answer
    When I send a spoken question
    Then the transcript of what I said is the first thing added to the session for that turn
    And the tutor's answer follows it

  # Why: A spoken answer delivered in parts must be heard in order, as one continuous answer
  @task:TASK-VC-006
  @key-example
  Scenario: A spoken answer delivered in several parts plays back in order
    Given the tutor's answer is delivered in several spoken parts
    When the answer plays
    Then the parts play in the order they were produced
    And I hear the whole answer without gaps or parts out of order

  # Why: Voice is additive — adding it must not change how typed tutoring already works (sibling port)
  @task:TASK-VC-005
  @key-example @regression
  Scenario: Typing a question still works exactly as before
    When I type a question instead of speaking
    Then it is answered exactly as it was before voice was added
    And nothing about the typed tutoring experience has changed

  # Why: On the live channel the answer should read and play as it is composed, text ahead of audio (streaming, W3)
  @task:TASK-VC-006
  @key-example @smoke
  Scenario: A spoken answer's text appears while it is still being composed and spoken
    Given I am connected to the live channel for my session
    When I send a spoken question
    Then the answer's text appears bit by bit as it is composed
    And the text runs ahead of the spoken audio being played

  # Why: "Green but broken" defence — the recording must reach the tutor as-recorded, as me, on my session
  # [ASSUMPTION: confidence=medium] Recordings are captured as m4a/AAC by default with opus as a fallback; the final encoder is Phase-0-gated on the m4a-against-live-STT test (design §6.1)
  @task:TASK-VC-003
  @key-example @smoke
  Scenario: A spoken question is delivered to the tutor exactly as recorded
    When I send a spoken question
    Then the tutor receives it authenticated as me and attached to my current session
    And the recording is delivered in the exact audio format it was captured in

  # ── Boundary conditions ───────────────────────────────────────────────

  # Why: Just-inside the 60-second ceiling — a normal-length question sends when I choose to stop
  # [ASSUMPTION: confidence=high] The maximum recording length is 60 seconds (design §6.3 client hard stop; contract QueryTooLong)
  @task:TASK-VC-004
  @boundary
  Scenario: A recording shorter than the time limit is sent when I stop it
    Given I am recording a spoken question
    When I stop recording after 59 seconds and send it
    Then the recording is sent to the tutor for an answer

  # Why: The 60-second stop is enforced on the phone itself — recording can never run past it
  @task:TASK-VC-004
  @boundary
  Scenario: Recording stops automatically at the 60-second limit
    Given I am recording a spoken question
    When the recording reaches 60 seconds
    Then the app stops the recording automatically at the limit
    And the recording is ready to send without ever exceeding 60 seconds

  # Why: Just-inside the chunking floor from the playback side — a one-part answer is a queue of one
  @task:TASK-VC-006
  @boundary
  Scenario: A short answer delivered as a single spoken part plays correctly
    Given the tutor's answer is delivered as a single spoken part
    When the answer plays
    Then it plays as one continuous spoken answer

  # ── Negative cases ────────────────────────────────────────────────────

  # Why: Degradation is a feature with copy — voice can vanish, text must not
  # [ASSUMPTION: confidence=high] The degradation notice reads "Spoken answers aren't available right now — text still works" and is shown in amber (design §5.5/§6.3)
  # [ASSUMPTION: confidence=high] After a voice-unavailable failure the mic stays visible but disabled for the rest of the session until a retry succeeds (design §6.3)
  @task:TASK-VC-005
  @negative @smoke
  Scenario: When spoken answers are unavailable the app degrades to text with a clear notice
    Given spoken answers are currently unavailable
    When I send a spoken question
    Then I see an amber notice that spoken answers aren't available right now and text still works
    And the mic stays visible but disabled for the rest of the session until a retry succeeds
    And I can still ask questions by typing

  # Why: A network wobble mid-send must not lose what I recorded — I can just retry
  # [ASSUMPTION: confidence=high] A transport failure keeps the existing connection-problem dialog, preserves the recording, and retry means resend (design §6.3)
  @task:TASK-VC-005
  @negative
  Scenario: A connection problem while sending a spoken question preserves my recording
    Given I have recorded a spoken question
    When sending it runs into a connection problem
    Then I am shown the connection-problem message
    And my recording is preserved so I can send it again without re-recording

  # Why: When the tutor refuses a recording, the app must say why in plain terms and stay usable (rulebook is FEAT-VOICE-001)
  # [ASSUMPTION: confidence=low] The refusal-reason wording below is inferred; the underlying error types are contract-firm but the user-facing copy is not specified
  # [ASSUMPTION: confidence=high] The size cap surfaced as "too large" is 10 MB (binding §4 RecordingTooLarge)
  @task:TASK-VC-005
  @negative
  Scenario Outline: The app explains why a recording could not be used and stays ready
    Given the tutor refuses my recording because <reason>
    When I send a spoken question
    Then I am told in plain terms that <message>
    And I can record and send another question straight away

    Examples:
      | reason                      | message                              |
      | its format is not supported | the recording format isn't supported |
      | it contains no audio        | the recording was empty              |
      | it could not be understood  | it couldn't be understood            |
      | it is longer than allowed   | the recording was too long           |
      | it is larger than allowed   | the recording was too large          |

  # Why: Without microphone permission the app must explain, not fail — typing stays available
  # [ASSUMPTION: confidence=low] The permission-denied message reads "The app needs microphone access to record"; exact in-app copy is not specified in design
  @task:TASK-VC-005
  @negative
  Scenario: Recording without microphone permission is explained and typing still works
    Given I have not granted the app microphone access
    When I try to record a spoken question
    Then the app tells me it needs microphone access to record
    And I can still ask questions by typing

  # ── Edge cases ────────────────────────────────────────────────────────

  # Why: A spoken part that has expired by playback time must be skipped, not stall the answer
  # [ASSUMPTION: confidence=high] Announced audio parts are ephemeral (TTL ≤120 s); a missing part is skipped and playback continues (binding §4.2)
  @task:TASK-VC-006
  @edge-case
  Scenario: A spoken part that is no longer available is skipped and playback continues
    Given the tutor's answer was announced in several spoken parts
    And one part is no longer available when it is time to play it
    When the answer plays
    Then that part is skipped and the remaining parts continue to play

  # Why: Speech is an enhancement — losing it mid-answer must not cost the text or the turn
  @task:TASK-VC-006
  @edge-case
  Scenario: Spoken audio stops partway but the written answer is unaffected
    Given the tutor's spoken answer stops being produced after the first part
    When I receive the answer
    Then the full written answer is still shown
    And no further spoken parts play after the point it stopped
    And the turn is recorded in the session normally

  # Why: One turn at a time — the mic must not start a new recording while a send is in flight
  @task:TASK-VC-005
  @edge-case
  Scenario: The mic does nothing while a spoken question is still being answered
    Given I have sent a spoken question and am waiting for the answer
    When I press the mic button again
    Then nothing happens until the current turn finishes

  # Why: An ended session accepts no input — the mic is disabled with everything else
  @task:TASK-VC-005
  @edge-case
  Scenario: The mic is disabled once the session has ended
    Given my session has ended
    Then the mic button is disabled along with the rest of the input

  # Why: Today's release build has no network permission at all — a shipped voice app must record AND reach the tutor
  # [ASSUMPTION: confidence=high] The Android release manifest gains INTERNET + RECORD_AUDIO and iOS gains a microphone-usage description (design §6.1)
  @task:TASK-VC-001
  @edge-case @regression
  Scenario: The shipped app is able to record audio and reach the tutor
    Given a release build of the app
    Then it is able to record from the microphone
    And it is able to reach the tutor over the network

  # ── Security, concurrency, and integration boundaries ─────────────────

  # Why: A spoken-part reference is not a bare capability — the app authenticates every fetch as me
  @task:TASK-VC-006
  @edge-case @negative
  Scenario: The app fetches each spoken part authenticated as me
    When the tutor's answer is delivered in spoken parts
    Then the app fetches each part authenticated as me
    And a spoken part is never retrieved without my credentials

  # Why: A recording I abandon before sending must start no turn and leave the session untouched
  @task:TASK-VC-004
  @edge-case
  Scenario: A recording cancelled before sending starts no turn
    Given I am recording a spoken question
    When I cancel the recording before sending it
    Then no question is sent and no turn is started
    And the recording is discarded

  # Why: An interruption mid-recording must not leave a half-recording or a half-sent turn
  @task:TASK-VC-004
  @edge-case
  Scenario: A recording interrupted by a call or backgrounding is abandoned cleanly
    Given I am recording a spoken question
    When an incoming call or the app moving to the background interrupts the recording
    Then the recording is abandoned cleanly without sending anything
    And I can start a new recording afterwards

  # Why: Cross-device lifecycle — a session ended on another device must be honoured when I try to send
  @task:TASK-VC-006
  @edge-case @negative
  Scenario: Sending a recording after the session was ended elsewhere is refused
    Given my session was ended on another device while I am recording
    When I finish recording and send it
    Then it is refused because the session has ended
    And the mic is disabled along with the rest of the input
