# Generated by /feature-spec
# Feature: Primary-Text RAG + Source-Typed Quote Verifier (FEAT-PH1-004)
# Stack: python
# Assumptions: 15 (see primary-text-rag-and-quote-verifier_assumptions.yaml)
# Generated: 2026-04-30T00:00:00Z

@phase-1 @feat-ph1-004 @rag @quote-verifier
Feature: Primary-Text RAG and Source-Typed Quote Verifier
  As the Study Tutor system
  I want to ground tutor responses in a source-typed corpus, decide
    selectively whether retrieval will help on this turn, and verify every
    quoted span the Player produces against canonical primary texts
  So that learners receive verbatim, correctly-attributed primary-text
    evidence when the corpus supports it, never see secondary-source
    paraphrases laundered as the author's own words, never see fabricated
    quotations, and never suffer the empirically-observed quality
    regression caused by always-on retrieval against a partial corpus

  Background:
    Given a source-typed corpus is configured under the GCSE English domain
    And the corpus is partitioned into four source-type folders: primary text, secondary study guide, secondary critical, and historical context
    And every chunk in the corpus carries a source-type label inferred from its parent folder
    And the corpus excludes AQA assessment materials in line with the publisher's stated prohibition
    # [ASSUMPTION: confidence=high] Public-domain primary texts are sourced from Standard Ebooks (ASSUM-004)
    And public-domain primary texts are sourced from a canonical edition with stable citation anchors
    And the tutoring loop consults the retrieval-decision function before every Player turn
    And the quote verifier inspects every Player response before the Coach evaluates it

  # ==========================================================================
  # GROUP A: Key Examples — core behaviour
  # ==========================================================================

  # Why: Core happy path — Shakespeare is in the corpus, retrieval runs, primary chunks lead the result
  @task:TASK-PRV-004
  @key-example @smoke @retrieval @primary
  Scenario: A turn on a primary text whose canonical edition is in the corpus retrieves source-filtered chunks
    Given the session is on a primary text whose canonical edition is in the corpus
    And the focus assessment objectives include AO1 and AO2
    When the retrieval-decision function is asked whether to retrieve for this turn
    Then the decision should be to retrieve
    And the retrieved chunks should prefer primary-text chunks ahead of secondary chunks
    And the retrieved chunks should be limited to the text the session is on
    And the response should be grounded in those chunks

  # Why: The empirical headline finding — when only secondary material exists, retrieval actively degrades quality, so we must skip
  @task:TASK-PRV-003
  @key-example @smoke @retrieval @analysis-mode
  Scenario: A turn on an in-copyright text with no primary edition in the corpus skips retrieval and runs in Analysis Mode
    Given the session is on an in-copyright modern text whose primary edition is not in the corpus
    When the retrieval-decision function is asked whether to retrieve for this turn
    Then the decision should be to skip retrieval
    # [ASSUMPTION: confidence=medium] Skip reason recorded as the explicit string "analysis_mode:no_primary_text" (ASSUM-006)
    And the turn metadata should record that retrieval was skipped with a reason
    And the Coach should not down-rank the response on quote fidelity for this turn

  # Why: AO3 is context, not theme — retrieval against a set-text corpus actively misleads it (R3)
  @task:TASK-PRV-003
  @key-example @smoke @retrieval @ao3-bypass
  Scenario: A turn whose focus is AO3 context bypasses retrieval and is answered from training
    Given the session is on a primary text whose canonical edition is in the corpus
    # [ASSUMPTION: confidence=medium] AO3 bypass triggers only when AO3 is the sole focus AO; mixed AO3+other still retrieves (ASSUM-007)
    And the focus assessment objectives are limited to AO3 alone
    When the retrieval-decision function is asked whether to retrieve for this turn
    Then the decision should be to skip retrieval
    # [ASSUMPTION: confidence=medium] Bypass reason recorded as the explicit string "ao3_only:training_first" (ASSUM-006)
    And the turn metadata should record that retrieval was bypassed for AO3 context

  # Why: The verifier's most important success path — verbatim primary quote → canonical citation
  @task:TASK-PRV-005
  @key-example @smoke @verify @primary
  Scenario: A verbatim quote from the primary text is annotated with its canonical citation
    Given a Player response contains a verbatim quotation from the primary text in the corpus
    When the quote verifier inspects the response
    # [ASSUMPTION: confidence=medium] Plays use act / scene / line; novels use chapter / paragraph (ASSUM-005)
    Then the quote should be annotated with its canonical citation by act, scene, and line for plays
    And the quoted span should be retained as the original author's words
    And the verifier result should record this match as a primary-text match

  # Why: This is the laundering failure mode the empirical session surfaced — secondary phrasing must NEVER read as the author's words
  @task:TASK-PRV-005
  @key-example @smoke @verify @secondary @safety
  Scenario: A phrase that appears verbatim in secondary material only is rewritten as attributed paraphrase
    Given a Player response contains a quoted phrase that appears verbatim only in secondary study-guide material
    And the phrase does not appear in any primary-text chunk
    When the quote verifier inspects the response
    Then the quotation marks around the phrase should be removed
    # [ASSUMPTION: confidence=low] Critic-style attribution phrases (e.g. "as one critic observes", "as one study guide notes") (ASSUM-010)
    And the phrase should be rewritten as paraphrase with a critic-style attribution
    And the verifier result should record this as a secondary-source rewrite event
    And no secondary phrase should be returned to the learner as the original author's words

  # Why: Fabricated quotes near a real quote are correctable; this preserves pedagogical value rather than stripping the whole point
  @task:TASK-PRV-005
  @key-example @verify @fuzzy
  Scenario: A near-verbatim primary-text quote is corrected to the canonical wording and annotated
    Given a Player response contains a quoted phrase that does not match any chunk verbatim
    And the phrase is within a small edit distance of a verbatim primary-text passage
    When the quote verifier inspects the response
    Then the quoted phrase should be replaced with the canonical wording from the primary text
    And the corrected quote should be annotated with its canonical citation
    And the verifier result should record this as a fuzzy correction match

  # Why: Fabricated quotes with no near-match are the original failure case (TASK-PO02-007 "unmaculate me from the deed")
  @task:TASK-PRV-005
  @key-example @verify @fabrication @safety
  Scenario: A fabricated quote with no corpus match is stripped of quotation marks and rewritten as paraphrase
    Given a Player response contains a quotation that does not match any corpus chunk verbatim
    And the quotation is not within a small edit distance of any primary-text passage
    When the quote verifier inspects the response
    Then the quotation marks should be removed
    And the content should be rewritten as paraphrase with the certainty softened
    And the verifier result should record this as a no-match strip event

  # Why: The corpus loader is the contract surface for source-type labelling — labelling drives every downstream decision
  @task:TASK-PRV-002
  @key-example @ingestion
  Scenario: The corpus loader infers a chunk's source type from the folder it lives in
    Given a source file is placed under the primary text folder
    And another source file is placed under the secondary study guide folder
    When the corpus is loaded
    Then chunks from the first file should carry the primary-text source type
    And chunks from the second file should carry the secondary study-guide source type
    And no chunk should carry an unset or default source-type label

  # ==========================================================================
  # GROUP B: Boundary Conditions
  # ==========================================================================

  # Why: Verifier minimum-span boundary — quoting "the play" must not trigger verification, but a four-word phrase must
  # [ASSUMPTION: confidence=high] Minimum verification span is four words (ASSUM-002)
  @task:TASK-PRV-005
  @boundary @verify
  Scenario Outline: The verifier inspects spans at and above the minimum word count and ignores those below
    Given a Player response contains a quoted span of <words> words
    When the quote verifier inspects the response
    Then the verifier behaviour should be <behaviour>

    Examples:
      | words | behaviour                |
      | 3     | ignored as below minimum |
      | 4     | inspected for matching   |
      | 5     | inspected for matching   |

  # Why: Fuzzy correction edit-distance boundary — primary-text near-misses are correctable, but a four-edit drift is too far
  # [ASSUMPTION: confidence=high] Fuzzy correction is allowed up to three character edits (ASSUM-003)
  @task:TASK-PRV-005
  @boundary @verify @fuzzy
  Scenario Outline: Fuzzy correction is bounded by edit distance from a canonical primary-text passage
    Given a Player response contains a quoted phrase
    And the phrase is at edit distance <distance> from a verbatim primary-text passage
    When the quote verifier inspects the response
    Then the verifier outcome should be <outcome>

    Examples:
      | distance | outcome                                |
      | 0        | annotated as a primary-text match      |
      | 1        | corrected and annotated                |
      | 2        | corrected and annotated                |
      | 3        | corrected and annotated                |
      | 4        | treated as a no-match strip event      |

  # Why: Top-K is the load-bearing retrieval parameter from the empirical work — must hold at exact boundary
  # [ASSUMPTION: confidence=high] Top-K equals 6 (ASSUM-001)
  @task:TASK-PRV-004
  @boundary @retrieval
  Scenario Outline: Source-filtered retrieval returns at most the configured top-K chunks
    Given the corpus contains <available> primary-text chunks relevant to the query
    When source-filtered retrieval runs for the turn
    Then the number of chunks returned should be <returned>

    Examples:
      | available | returned |
      | 6         | 6        |
      | 7         | 6        |
      | 3         | 3        |
      | 0         | 0        |

  # Why: Empty source folder must not break ingestion — and must produce no chunks rather than failing
  @task:TASK-PRV-002
  @boundary @ingestion
  Scenario: An empty primary-text folder produces no chunks and no error
    Given the primary-text folder exists and is empty
    When the corpus is loaded
    Then no chunks should be emitted from that folder
    And the loader should report a successful ingestion summary

  # Why: Whitespace-only file boundary — file present but unusable
  @task:TASK-PRV-002
  @boundary @ingestion
  Scenario: A whitespace-only source file produces no chunks
    Given a primary-text file exists but contains only whitespace
    When the corpus is loaded
    Then no chunks should be emitted from that file
    And the loader should record a structured log entry naming the skipped file

  # ==========================================================================
  # GROUP C: Negative Cases
  # ==========================================================================

  # Why: AQA explicitly prohibits AI use of its assessment materials — corpus must refuse them, not silently absorb
  @task:TASK-PRV-002
  @negative @ingestion @copyright
  Scenario: A file matching an AQA assessment-material pattern is refused at ingestion
    # [ASSUMPTION: confidence=low] AQA-material refusal is enforced by filename-pattern matching against past-paper / mark-scheme / examiner-report conventions (ASSUM-008)
    Given a file whose name matches an AQA past-paper, mark-scheme, or examiner-report pattern is placed in the corpus
    When the corpus is loaded
    Then the file should not be ingested
    And the loader should record a structured refusal entry naming the prohibited file
    And the refusal should reference the publisher's prohibition

  # Why: Without a primary-text edition, retrieval cannot help and must report so explicitly — the silent failure is the actual bug
  @task:TASK-PRV-004
  @negative @retrieval
  Scenario: A retrieval request for a text absent from the corpus returns an empty result with an explicit reason
    Given the session is on a text not present in any source-type folder
    When source-filtered retrieval runs for the turn
    Then the retrieval result should be empty
    And the turn metadata should record that retrieval was skipped with the reason "no primary-text edition available"

  # Why: A quote that exists only in secondary material must NEVER be returned to the learner as the original author's words
  @task:TASK-PRV-005
  @negative @verify @safety
  Scenario: A secondary-only phrase presented as the author's words is never annotated as a primary citation
    Given a Player response presents a phrase as the original author's words
    And the phrase exists verbatim only in a secondary chunk
    When the quote verifier inspects the response
    Then the phrase should not be annotated as a primary-text match under any circumstance
    And the verifier result should record a secondary-source rewrite

  # Why: Defence in depth — secondary handling must hold regardless of where in the response the quote appears
  @task:TASK-PRV-005
  @negative @verify @safety
  Scenario: Multiple secondary-only quotes in a single response are all rewritten, not just the first
    Given a Player response contains three quoted phrases all of which appear verbatim only in secondary chunks
    When the quote verifier inspects the response
    Then every one of the three quoted phrases should be rewritten as attributed paraphrase
    And the verifier result should record three secondary-source rewrite events

  # Why: AQA-material exclusion must apply at retrieval time as well as ingestion — defence in depth
  @task:TASK-PRV-004
  @negative @retrieval @copyright
  Scenario: AQA-style assessment material accidentally present is excluded from retrieval results
    Given a file matching an AQA assessment-material pattern was overlooked at ingestion
    When source-filtered retrieval runs for the turn
    Then no chunk derived from that file should appear in the retrieval result
    And the retrieval pipeline should record the exclusion

  # ==========================================================================
  # GROUP D: Edge Cases
  # ==========================================================================

  # Why: Mixed-AO turns are common — AO1+AO2 must drive retrieval, the AO3 portion answers from training (mixed mode)
  @task:TASK-PRV-003
  @edge-case @retrieval @ao3
  Scenario: A turn with mixed focus assessment objectives retrieves for AO1/AO2 evidence and supplies AO3 from training
    Given the session is on a primary text whose canonical edition is in the corpus
    And the focus assessment objectives include AO1, AO2, and AO3
    When the retrieval-decision function is asked whether to retrieve for this turn
    Then the decision should be to retrieve for the AO1 and AO2 evidence
    And the AO3 contextual material should be expected from the model's training
    And the turn metadata should record this as a mixed-mode turn

  # Why: Same span matching both primary and secondary chunks must always resolve to primary — never to secondary
  @task:TASK-PRV-005
  @edge-case @verify @primary-wins
  Scenario: A quoted span matching both primary and secondary chunks is treated as a primary-text match
    Given a Player response contains a quoted span that appears verbatim in both a primary-text chunk and a secondary chunk
    When the quote verifier inspects the response
    Then the verifier outcome should be a primary-text match
    And the secondary chunk should not influence the outcome

  # Why: The empirical session showed whitespace differences caused legitimate matches to fail — must normalise
  @task:TASK-PRV-005
  @edge-case @verify @whitespace
  Scenario: A quoted span that differs from the primary-text only in whitespace or punctuation matches successfully
    # [ASSUMPTION: confidence=medium] Matching runs on a normalised form: collapsed whitespace, surrounding punctuation stripped, curly vs straight quotes equated (ASSUM-012)
    Given a Player response contains a quoted span that matches a primary-text passage in word sequence but differs in whitespace and punctuation
    When the quote verifier inspects the response
    Then the verifier outcome should be a primary-text match
    And the quote should be annotated with its canonical citation

  # Why: Long passages must be embedded as short evidence, not reproduced — the §6.1 boundary in GOAL.md
  @task:TASK-PRV-005
  @edge-case @verify @safety @copyright
  Scenario: A Player response that quotes an entire long passage is reduced to a short embedded quotation
    # [ASSUMPTION: confidence=low] Quotations exceeding 30 words are reduced to a short embedded quotation of 12 words or fewer (ASSUM-011)
    Given a Player response contains a verbatim primary-text quotation longer than a short evidence span
    When the quote verifier inspects the response
    Then the response should be rewritten to contain only a short embedded quotation from that passage
    And the verifier result should record a long-passage shortening event

  # Why: Loader resilience — a single broken file must not stop the rest of the corpus from loading
  @task:TASK-PRV-002
  @edge-case @ingestion @resilience
  Scenario: A corrupted source file does not prevent the rest of the corpus from loading
    Given the primary-text folder contains one valid file and one corrupted file
    When the corpus is loaded
    Then chunks from the valid file should be emitted
    And the corrupted file should be skipped with a structured log entry
    And the loader should report a successful ingestion summary that names the skipped file

  # Why: Filesystem path traversal must not allow a relabel attack on source type
  @task:TASK-PRV-002
  @edge-case @ingestion @security
  Scenario: A source file whose path traverses outside the corpus root is rejected at ingestion
    Given a source file whose resolved path lies outside the corpus root is placed in the corpus
    When the corpus is loaded
    Then the file should be rejected
    And the loader should record a structured refusal naming the path-traversal attempt
    And no chunks from that file should be emitted

  # Why: Concurrency — multiple turns can verify in parallel; verifier must not share mutable state
  @task:TASK-PRV-005
  @edge-case @verify @concurrency
  Scenario: Two simultaneous quote-verification calls on different responses produce independent results
    Given two Player responses are submitted to the verifier at the same time
    And the responses contain different quoted spans
    When both verification calls run concurrently
    Then each call should produce its own result independent of the other
    And neither call's annotations should bleed into the other's response

  # Why: Embedder unavailability must degrade gracefully to Analysis Mode rather than blocking the turn
  @task:TASK-PRV-003
  @edge-case @retrieval @resilience
  Scenario: When the embedding service is unavailable retrieval is skipped and the turn proceeds in Analysis Mode
    # [ASSUMPTION: confidence=low] The embedding service is treated as unavailable when a single retrieval call exceeds 5 seconds (ASSUM-013)
    Given the session is on a primary text whose canonical edition is in the corpus
    And the embedding service is unavailable
    When the retrieval-decision function runs for the turn
    Then the decision should be to skip retrieval
    And the turn metadata should record an Analysis-Mode reason citing service unavailability
    And the Coach should not down-rank the response on quote fidelity for this turn

  # Why: AO3-only turn must not trigger retrieval even when an empty historical-context folder exists
  @task:TASK-PRV-003
  @edge-case @retrieval @ao3
  Scenario: An AO3-only turn with an empty historical-context folder still bypasses retrieval
    Given the historical-context folder exists and is empty
    And the focus assessment objectives are limited to AO3 alone
    When the retrieval-decision function is asked whether to retrieve for this turn
    Then the decision should be to skip retrieval
    And the turn metadata should record that retrieval was bypassed for AO3 context

  # ==========================================================================
  # GROUP E: Edge Case Expansion — security, integration, data integrity
  # ==========================================================================

  # Why: Corpus chunks must be inert data — a chunk containing instruction-like text must not steer the verifier
  @task:TASK-PRV-005
  @edge-case @verify @security @prompt-injection
  Scenario: Instruction-like text inside a corpus chunk is treated as data and does not steer the verifier
    Given a primary-text chunk happens to contain phrasing that resembles an instruction to an AI agent
    And a Player response contains a verbatim quotation drawn from that chunk
    When the quote verifier inspects the response
    Then the verifier should treat the chunk content purely as evidence
    And the verifier outcome should be a primary-text match with the canonical citation
    And no instruction-like content should alter the verifier's behaviour for any other span in the response

  # Why: A response can mention quotes from a text other than the session's text — citation must not be misapplied
  @task:TASK-PRV-005
  @edge-case @verify @security @cross-text
  Scenario: A quoted span belonging to a different primary text than the session is on is not annotated with the session text's citation
    # [ASSUMPTION: confidence=medium] Cross-text mismatch outcome is paraphrase rewrite rather than wrong-text annotation (ASSUM-015)
    Given the session is on a primary text whose canonical edition is in the corpus
    And the corpus also contains a different primary text
    And a Player response contains a quoted span that appears verbatim only in the other primary text
    When the quote verifier inspects the response
    Then the span should not be annotated with a citation from the session's text
    And the span should be rewritten as paraphrase with the certainty softened
    And the verifier result should record a cross-text mismatch event

  # Why: The Coach must score the rewritten response, not the original — otherwise the rewrite contributes nothing
  @task:TASK-PRV-006
  @edge-case @verify @integration @coach-handover
  Scenario: The Coach evaluates the verifier-rewritten response, not the original Player response
    Given a Player response contains one fabricated quotation and one verbatim primary-text quotation
    When the quote verifier inspects the response
    And the verifier produces a rewritten response with the fabricated quote stripped and the verbatim quote annotated
    Then the response handed to the Coach should be the rewritten response
    And the Coach should not see the original fabricated quotation
    And the verifier metadata for the turn should accompany the response so the Coach can score quote fidelity

  # Why: Reranker is an empirical add-on; its absence must degrade gracefully rather than block the turn
  @task:TASK-PRV-004
  @edge-case @retrieval @resilience
  Scenario: Source-filtered retrieval proceeds without a reranker when the reranker is unavailable
    # [ASSUMPTION: confidence=high] Reranker is BAAI/bge-reranker-v2-m3, CPU-only (ASSUM-014)
    Given the configured reranker is unavailable at retrieval time
    And the session is on a primary text whose canonical edition is in the corpus
    When source-filtered retrieval runs for the turn
    Then chunks should still be returned ordered by base similarity
    And the turn metadata should record that retrieval ran without reranking
    And the response should still be grounded in the returned chunks

  # Why: Citation anchors live on the chunk — the verifier must consume them directly rather than re-parse text
  @task:TASK-PRV-005
  @edge-case @verify @integration @citation
  Scenario: The verifier reads canonical citation anchors directly from the matched chunk's metadata
    Given a primary-text chunk carries structured citation-anchor metadata
    And a Player response contains a verbatim quotation drawn from that chunk
    When the quote verifier inspects the response
    Then the citation annotation on the matched quote should be derived from the chunk's citation-anchor metadata
    And the verifier should not re-parse the chunk text to construct the citation

  # Why: Plays and novels carry different anchor shapes — corpus must support both side by side
  @task:TASK-PRV-005
  @edge-case @verify @integration @citation
  Scenario: A play and a novel coexist in the corpus and produce citations in their respective conventions
    Given the corpus contains a play and a 19th-century novel as primary texts
    And one Player response contains a verbatim quotation from the play
    And another Player response contains a verbatim quotation from the novel
    When the quote verifier inspects each response
    Then the play quotation should be annotated with an act, scene, and line citation
    And the novel quotation should be annotated with a chapter and paragraph citation
