# Generated by /feature-spec
# Feature: HTTP App Access Adapter (FEAT-APP-001)
# Stack: python
# Assumptions: 11 (see http-app-access-adapter_assumptions.yaml)
# Generated: 2026-07-05T07:02:01Z
# Scope: FEAT-APP-001 — the six contract §5 verbs as plain JSON endpoints on :8100,
#   a SECOND consumer of the proven SessionService (MCP surface untouched, contract
#   §10); the HTTP binding table (docs/design/contracts/API-session-http-binding.md,
#   published in the FIRST task and frozen once pushed — the Mac-side app codes
#   against it at a pinned SHA); interim auth via a static token→student config
#   table (prod: lilymay only; dev: test-token-student-a→lilymay + test-token-student-b→alex with
#   reject-unknown); a dev-only reset truncating session/session_turn rows only;
#   an idempotent Postgres student-identity seed; a serve-http CLI subcommand +
#   a new compose under deploy/http/; a READY boot smoke.
# RESOLVED in assumption review (all defaults confirmed by operator, 2026-07-05):
#   unseeded student → Unauthenticated; validation errors are transport-level,
#   outside the §9 closed set; starlette+uvicorn pinned as direct deps;
#   GET /healthz; POST /__dev__/reset; default list limit 20; env-var config
#   (STUDY_TUTOR_HTTP_TOKENS JSON map + STUDY_TUTOR_HTTP_DEV_RESET flag);
#   seed ships as a `study-tutor seed-students` CLI subcommand; the HTTP adapter
#   reuses the MCP-wired tutor loop and emits the same pinned event payloads;
#   port 8100 default, flag-overridable.
# Out of scope: WS / turn_stream (voice, phase 3); Keycloak / real multi-student
#   auth (D9); session TTL; concurrent-resume leases / session_version UX;
#   app/** (Mac-side, in-flight); the pinned cross-device contract
#   (CONTRACT_SHA 22791af); baseline topic_confidence seeding (stays with
#   FEAT-SMP-004 ASSUM-010).
# REVIEW REQUIRED: 4 low-confidence assumptions (ASSUM-001 unseeded-student error,
#   ASSUM-004 health route, ASSUM-007 config mechanism, ASSUM-008 seed vehicle) —
#   confirmed at proposed defaults by the operator; Coach verifies ASSUM-001
#   against the binding doc before freeze.

@phase-2 @feat-app-001 @http @app-access
Feature: HTTP App Access Adapter
  As a student using the study-tutor app on my phone
  I want the tutoring session verbs available over the household network
  So that the app works against the same durable sessions as every other device

  Background:
    Given a study-tutor Postgres store with the schema applied
    And the students "lilymay" and "alex" are seeded as identity rows
    And the HTTP session service is running with the dev token table

  # ==========================================================================
  # GROUP A: Key Examples
  # ==========================================================================

  # Why: Core identity rule — the session belongs to the TOKEN's student, never client-asserted
  @task:TASK-APP1-03
  @key-example @smoke
  Scenario: Starting a session creates a durable session for the token's student
    When the app authenticates with lilymay's token and starts a session on the subject "english-literature"
    Then a new active session should be returned
    And the session should belong to lilymay

  # Why: The tutoring loop works over the new transport, with per-turn durability intact
  # [ASSUMPTION: confidence=medium] The HTTP adapter reuses the exact tutor loop the MCP adapter wires
  @task:TASK-APP1-03
  @key-example @smoke
  Scenario: Taking a turn returns the tutor's reply and durably records the exchange
    Given lilymay has an active session started over HTTP
    When the app sends the message "What does the dagger symbolise?" to that session
    Then the tutor's reply should be returned
    And both her message and the tutor's reply should be durably recorded on the session

  # Why: "Resume where you left off" — the list drives the app's home screen
  @task:TASK-APP1-03
  @key-example
  Scenario: Listing sessions shows the student's own sessions with their activity
    Given lilymay has an active session with two recorded exchanges
    When the app lists lilymay's sessions
    Then the list should include that session with its turn count and last activity

  # Why: The cross-device pickup — full ordered transcript for a device that didn't start it
  @task:TASK-APP1-03
  @key-example @smoke
  Scenario: Resuming a session returns the full transcript in order
    Given lilymay has an active session with several recorded exchanges
    When the app resumes that session
    Then the full transcript should be returned in the order the messages were exchanged

  # Why: The app's status view — resumability is what enables the Resume button
  @task:TASK-APP1-03
  @key-example
  Scenario: Session status reports the session as active and resumable
    Given lilymay has an active session
    When the app asks for that session's status
    Then the status should show the session as active and resumable

  # Why: End-of-session is where learner state is banked; must behave exactly as over MCP
  # [ASSUMPTION: confidence=medium] The HTTP transport emits the same pinned event payloads as the MCP path
  @task:TASK-APP1-03
  @key-example @smoke
  Scenario: Ending a session records the learner-state completion
    Given lilymay has an active session with at least one exchange
    When the app ends that session
    Then the session should be ended
    And her learner state should reflect the completed session
    And the session-completed event should be published as it is for every other transport

  # Why: The retro lesson — READY means answering, not "didn't crash for N seconds"
  # [ASSUMPTION: confidence=low] Health route is GET /healthz on port 8100 (port high-confidence, decision §6.2)
  @task:TASK-APP1-04
  @key-example @smoke @boot
  Scenario: The service reports ready only once it is answering requests
    When the HTTP session service is started with a valid store configuration
    Then it should report ready only once it is accepting requests
    And a health check should succeed

  # Why: The binding doc is what the Mac-side app codes against — this keeps it honest
  @task:TASK-APP1-07
  @key-example @regression
  Scenario: Every served endpoint matches the published binding table
    When the routes served by the running service are compared with the published binding table
    Then every verb, path, and error mapping should match the document exactly

  # ==========================================================================
  # GROUP B: Boundary Conditions
  # ==========================================================================

  # Why: resume_if_active true-branch — no duplicate session, transcript attached
  @task:TASK-APP1-03
  @boundary
  Scenario: Starting with resume-if-active returns the existing active session
    Given lilymay has an active session on the subject "english-literature" with two exchanges
    When the app starts a session on that subject asking to resume if one is active
    Then the existing session should be returned marked as resumed
    And its transcript should accompany it
    And no new session should be created

  # Why: The pick order is pinned by the app's contract test — must not be reordered
  @task:TASK-APP1-03
  @boundary @regression
  Scenario: Resume-if-active picks the most recently active session
    Given lilymay has two active sessions on the same subject
    When the app starts a session on that subject asking to resume if one is active
    Then the session with the most recent activity should be the one resumed

  # Why: resume_if_active false-branch — degenerates to a plain start
  @task:TASK-APP1-03
  @boundary
  Scenario: Starting with resume-if-active creates a new session when none is active
    Given lilymay has no active session on the subject "english-literature"
    When the app starts a session on that subject asking to resume if one is active
    Then a new session should be created and not marked as resumed

  # Why: The zero-turn rule — an abandoned session must not pollute learner state
  @task:TASK-APP1-03
  @boundary
  Scenario: Ending a session with no exchanges leaves learner state unchanged
    Given lilymay has an active session with no exchanges
    When the app ends that session
    Then the session should be ended
    And her learner state should be unchanged

  # Why: Just-at-default boundary for the listing limit
  # [ASSUMPTION: confidence=high] Default listing limit is 20 (the store port's constant)
  @task:TASK-APP1-03
  @boundary
  Scenario: Listing sessions without a limit returns the default number most recently active
    Given lilymay has more sessions than the default listing limit
    When the app lists her sessions without specifying a limit
    Then only the default number of sessions should be returned
    And they should be the most recently active ones

  # Why: Status filter — the app's home screen asks for active only
  @task:TASK-APP1-03
  @boundary
  Scenario: Listing sessions filtered by status returns only matching sessions
    Given lilymay has an ended session and an active session
    When the app lists only her active sessions
    Then just the active session should be returned

  # Why: Resume-if-active is scoped to the subject — an unrelated active session must not hijack a new start
  @task:TASK-APP1-03
  @boundary
  Scenario: Resume-if-active is subject-scoped
    Given lilymay has an active session on the subject "maths"
    When the app starts a session on the subject "english-literature" asking to resume if one is active
    Then a new session should be created and not marked as resumed
    And the "maths" session should remain untouched

  # ==========================================================================
  # GROUP C: Negative Cases
  # ==========================================================================

  # Why: The auth floor — every verb requires a credential
  @task:TASK-APP1-02
  @negative @auth
  Scenario Outline: A request without a token is rejected as unauthenticated
    When the app calls <verb> without presenting a token
    Then the request should be rejected as unauthenticated

    Examples:
      | verb            |
      | start_session   |
      | list_sessions   |
      | resume_session  |
      | turn            |
      | session_status  |
      | end_session     |

  # Why: reject-unknown-tokens is what makes the Mac's Unauthenticated tests runnable live
  @task:TASK-APP1-02
  @negative @auth
  Scenario: An unknown token is rejected as unauthenticated
    When the app presents a token that is not in the token table
    Then the request should be rejected as unauthenticated

  # Why: Contract §3 — identity comes from the token; a client-asserted identity is ignored
  @task:TASK-APP1-02
  @negative @auth @security
  Scenario: A client-asserted student identity is ignored in favour of the token's
    When alex's app starts a session while claiming to be lilymay in the request
    Then the session should be created for alex
    And lilymay should have no new session

  # Why: The ownership guard, on every verb that names a session
  @task:TASK-APP1-03
  @negative @ownership
  Scenario Outline: Another student's session cannot be touched
    Given lilymay has an active session
    When alex's app calls <verb> on that session
    Then the attempt should be refused as not the caller's session

    Examples:
      | verb            |
      | resume_session  |
      | turn            |
      | session_status  |
      | end_session     |

  # Why: Unknown session distinguishes "not found" from "not yours"
  @task:TASK-APP1-03
  @negative
  Scenario: A session identifier that does not exist is reported as not found
    When the app resumes a session identifier that does not exist
    Then the error should indicate the session was not found

  # Why: ended is terminal — mutating verbs refuse, status is the one carve-out
  @task:TASK-APP1-03
  @negative @lifecycle
  Scenario: Verbs on an ended session are refused except status
    Given lilymay had a session that has since ended
    When the app sends a message to that session
    Then the error should indicate the session has ended
    When the app asks for that session's status
    Then the status should show the session as ended and not resumable

  # Why: The seed gap found in review — a resolvable token with no learner row must fail cleanly
  # [ASSUMPTION: confidence=low] An authenticated-but-unseeded student is refused as unauthenticated, keeping the §9 closed set intact
  @task:TASK-APP1-02
  @negative @seed
  Scenario: A token mapping to an unseeded student is refused cleanly
    Given a token in the table maps to a student with no seeded identity row
    When that app starts a session
    Then the request should be refused as unauthenticated
    And no session should be created

  # Why: Malformed input must not corrupt state or crash the service
  # [ASSUMPTION: confidence=medium] Validation failures are transport-level, documented in the binding table, outside the §9 closed domain set
  @task:TASK-APP1-03
  @negative
  Scenario: A malformed request is rejected without touching any session state
    Given lilymay has an active session
    When the app sends a request whose body cannot be understood
    Then the request should be rejected with a clear validation error
    And her session should be unchanged

  # Why: Ownership must be judged before lifecycle state — no leaking another student's session state
  @task:TASK-APP1-03
  @negative @security @edge-case
  Scenario: Ownership refusal wins over ended-state on another student's session
    Given lilymay had a session that has since ended
    When alex's app sends a message to that session
    Then the attempt should be refused as not the caller's session
    And the error should not reveal whether the session has ended

  # ==========================================================================
  # GROUP D: Edge Cases
  # ==========================================================================

  # Why: Test isolation for the live suite — sessions go, learner state stays
  # [ASSUMPTION: confidence=medium] Reset route is POST /__dev__/reset, enabled by an environment flag
  @task:TASK-APP1-05
  @edge-case @dev-reset
  Scenario: The dev reset clears sessions but preserves learner state
    Given lilymay has sessions with recorded exchanges and previously banked XP and confidence
    When the dev reset is invoked
    Then all sessions and their exchanges should be gone
    And her XP, streak, and confidence should be untouched

  # Why: The reset must be impossible to reach in prod
  @task:TASK-APP1-05
  @edge-case @dev-reset @security
  Scenario: The dev reset does not exist under the prod configuration
    Given a service running with the prod configuration
    When the dev reset is invoked
    Then the reset should be refused as an unknown route

  # Why: Prod keeps the single-user posture — config, not an auth system
  # [ASSUMPTION: confidence=low] Token table and reset flag are supplied via environment variables per flavour
  @task:TASK-APP1-02
  @edge-case @auth
  Scenario: The prod configuration accepts only the single configured student
    Given a service running with the prod configuration
    When alex's token is presented
    Then the request should be rejected as unauthenticated
    And lilymay's token should still be accepted

  # Why: The seed must be safe to re-run on a database that already has learner data
  # [ASSUMPTION: confidence=low] The seed ships as a study-tutor seed-students CLI subcommand with idempotent inserts
  @task:TASK-APP1-05
  @edge-case @seed
  Scenario: Applying the student seed twice leaves exactly one row per student
    Given the student seed has already been applied
    When the seed is applied again
    Then each student should still appear exactly once
    And existing learner state should be untouched

  # Why: A dead store must degrade to a clear error, not a hung or crashed service
  @task:TASK-APP1-04
  @edge-case
  Scenario: The service degrades cleanly when the store is unreachable
    Given the Postgres store becomes unreachable
    When the app starts a session
    Then the request should fail with a clear server error
    And the service should answer normally once the store is reachable again

  # Why: Contract §10 — agent-hosts keep their four tools exactly as-is
  @task:TASK-APP1-07
  @edge-case @regression @mcp
  Scenario: The MCP tool surface is unchanged by this feature
    When an agent-host lists the MCP tools
    Then the four tools and their descriptions should be exactly as they were before this feature

  # Why: Credentials belong in the credential header only — never in addresses that reach logs and proxies
  @task:TASK-APP1-02
  @edge-case @security
  Scenario: A token is honoured only from the credential header
    When the app presents a valid token in the request address instead of the credential header
    Then the request should be rejected as unauthenticated

  # Why: Two devices racing the same subject must converge on one session (hermetic tier — too racy for the live suite)
  @task:TASK-APP1-03
  @edge-case @concurrency
  Scenario: Simultaneous resume-if-active starts converge on one session
    Given lilymay has no active session on the subject "english-literature"
    When two devices simultaneously start a session on that subject asking to resume if one is active
    Then both devices should end up attached to the same session
    And lilymay should have exactly one active session on that subject

  # Why: LLM failures WILL happen live — the session must stay consistent and resumable
  @task:TASK-APP1-04
  @edge-case
  Scenario: A tutor-loop failure mid-turn leaves the session consistent and resumable
    Given lilymay has an active session
    And the tutor loop will fail on the next message
    When the app sends a message to that session
    Then the request should fail with a clear server error
    And the session should remain active and resumable
    And a retried message should succeed once the tutor loop recovers

  # Why: Complements the READY smoke — never READY when requests can only fail
  @task:TASK-APP1-04
  @edge-case @boot
  Scenario: Starting the service against an unreachable store fails fast
    Given the Postgres store is unreachable
    When the HTTP session service is started
    Then it should refuse to report ready
    And the failure should clearly name the store as the cause
