# Generated by /feature-spec
# Feature: Keycloak IdP Standup on the NAS (FEAT-AUTH-001, A1)
# Stack: python
# Assumptions: 9 (see keycloak-idp-standup_assumptions.yaml)
# Generated: 2026-07-08T19:21:55Z
# Scope: FEAT-AUTH-001 A1 standup only — the study_tutor_keycloak container
#   (quay.io/keycloak/keycloak:26.6.x pinned, start --optimized, 2GB memory limit) on
#   the NAS; the co-located keycloak DB + role in study_tutor_postgres :5434; the
#   realm-as-code import from deploy/keycloak/realm/ (realm study-tutor; clients
#   study-tutor-app / reachy-robot / live-suite per KC-D4; roles student + parent;
#   student_id attribute->claim protocol mapper; users runbook-created, never in git);
#   the tailscale cert for whitestocks.tailebf801.ts.net + https issuer; the backup.sh
#   second pg_dump line; and the executable standup runbook with gate KC-G1 (device
#   browser reaches the https realm, discovery doc serves, NAS RAM recorded before/after).
# Out of scope: A2 server TokenResolver / auth_keycloak.py; A3 app OIDC sign-in; A4
#   robot device-grant pairing; the sub->student_id server-side derivation; the
#   JWKS-by-tailnet-IP extra_hosts split (an A2 server concern); parent endpoints (KC-D5).
# REVIEW REQUIRED: 2 low-confidence assumptions (ASSUM-004 realm import mechanism,
#   ASSUM-005 post-standup RAM headroom target) — confirmed at proposed defaults by the
#   operator; Coach verifies both against the standup runbook before freeze.
# References: docs/design/keycloak-auth-user-management-design.md (KC-D1..D7);
#   docs/architecture/decisions/ADR-ARCH-028-keycloak-idp-nas-placement-tailnet-tls.md;
#   docs/runbooks/RUNBOOK-study-tutor-postgres-deploy.md (the G0..G7 gate model this mirrors);
#   deploy/postgres/backup.sh (the atomic pg_dump pattern the second dump line joins).

@feat-auth-001 @keycloak @idp @nas-standup
Feature: Keycloak IdP Standup on the NAS (A1)
  As an operator standing up the study-tutor identity provider
  I want an executable runbook that brings Keycloak up on the NAS with its realm-as-code, TLS, co-located DB, and backups
  So that household devices can obtain validated identity tokens from household-owned hardware

  Background:
    Given the study-tutor Postgres store is running and healthy on the NAS
    And the NAS has the proven docker, SSH, and Task Scheduler deploy mechanics already in place

  # ==========================================================================
  # GROUP A: Key Examples
  # ==========================================================================

  # Why: Core standup outcome — the identity service comes up healthy on the pinned version
  @task:TASK-KC-001
  @key-example @smoke
  Scenario: The Keycloak identity service starts and reports healthy
    Given the standup runbook has been executed on the NAS
    When the operator checks the identity service status
    Then the identity service should be running and report healthy
    And it should be the pinned Keycloak 26.6 image, not a floating tag

  # Why: KC-G1 core — the realm discovery document serves over the https issuer
  # [ASSUMPTION: confidence=high] The realm is served over the tailnet https port 8443, per the KC-D2 issuer URL
  @task:TASK-KC-006
  @key-example @smoke
  Scenario: The realm discovery document is served over the tailnet https issuer
    Given the identity service is running
    When a client requests the study-tutor realm discovery document over the tailnet https issuer
    Then the discovery document should be returned successfully
    And its advertised issuer should match the pinned tailnet MagicDNS issuer

  # Why: KC-G1 — a real household device browser can reach sign-in over trusted https
  @task:TASK-KC-006
  @key-example @smoke
  Scenario: A household device browser reaches the realm sign-in page over https
    Given the identity service is running with the tailscale certificate mounted
    When a household device opens the study-tutor realm sign-in page over the tailnet
    Then the sign-in page should load over a trusted https connection with no certificate warning

  # Why: Realm-as-code produced exactly the expected clients, roles, and claim mapper
  # [ASSUMPTION: confidence=low] The realm is provisioned via --import-realm from deploy/keycloak/realm/ on the optimized start
  # [ASSUMPTION: confidence=high] The emitted claim is named student_id, per the KC-D6 default
  @task:TASK-KC-002
  @key-example
  Scenario: The realm is provisioned from code with the expected clients, roles, and claim mapper
    Given the realm-as-code under deploy/keycloak/realm was imported during standup
    Then the study-tutor realm should exist
    And the clients "study-tutor-app", "reachy-robot", and "live-suite" should be present
    And the realm roles "student" and "parent" should exist
    And the student_id user attribute should be mapped into a student_id token claim

  # Why: The keycloak DB + role co-locate in the existing Postgres, per the D4 rule
  @task:TASK-KC-003
  @key-example
  Scenario: The keycloak database and role are created in the existing Postgres container
    Given the study-tutor Postgres container is running
    When the operator inspects the databases and roles
    Then a dedicated keycloak database and keycloak role should exist alongside the study_tutor database
    And the identity service should be storing its realm state in that keycloak database

  # Why: backup.sh now protects the non-reindexable realm/user state alongside learner state
  # [ASSUMPTION: confidence=medium] The keycloak dump follows the existing 14-day retention in backup.sh
  @task:TASK-KC-004
  @key-example
  Scenario: The nightly backup captures both the learner store and the realm state
    Given the nightly backup routine runs on the NAS
    When the backup completes
    Then a logical dump of the study_tutor database should be produced
    And a separate logical dump of the keycloak database should be produced

  # ==========================================================================
  # GROUP B: Boundary Conditions
  # ==========================================================================

  # Why: Just-inside boundary — memory limits across the supported sizing band all start cleanly
  @task:TASK-KC-001
  @boundary
  Scenario Outline: The identity service starts across the supported memory sizing band
    Given the identity service container memory limit is set to <limit>
    When the identity service starts
    Then it should become healthy and serve the realm discovery document

    Examples:
      | limit |
      | 750MB |
      | 1GB   |
      | 2GB   |

  # Why: Just-outside boundary — below the official 750MB minimum the service cannot stand up
  @task:TASK-KC-001
  @boundary @negative
  Scenario: A memory limit below the supported minimum starves the identity service
    Given the identity service container memory limit is set below 750MB
    When the identity service starts
    Then it should fail to become healthy
    And the operator should be directed to raise the memory limit into the supported band

  # Why: KC-G1 requires NAS RAM recorded before and after; standup must leave positive headroom
  # [ASSUMPTION: confidence=high] The container memory limit is 2GB, per the feature description
  # [ASSUMPTION: confidence=low] A safe post-standup headroom is at least 1GB free against the 8GB NAS total
  @task:TASK-KC-006
  @boundary
  Scenario: NAS memory is recorded before and after standup and headroom stays positive
    Given the operator records the NAS free memory before standup
    When the identity service standup completes with its 2GB memory limit
    And the operator records the NAS free memory after standup
    Then both readings should be captured in the runbook evidence
    And the after reading should leave the NAS with positive free-memory headroom against its 8GB total

  # Why: Boundary between a pinned and a floating image — only the pinned 26.6 line passes the gate
  @task:TASK-KC-005
  @boundary @negative
  Scenario: A floating or mismatched image tag fails the version gate
    Given the standup was configured with an image tag outside the pinned 26.6 line
    When the operator verifies the running identity service version
    Then the version check should fail
    And the operator should be directed to pin the 26.6 image before proceeding

  # ==========================================================================
  # GROUP C: Negative Cases
  # ==========================================================================

  # Why: The minor's identity PII must never be committed — realm-as-code carries no users or secrets
  @task:TASK-KC-002
  @negative @smoke
  Scenario: The committed realm-as-code contains no users and no client secrets
    Given the realm export committed under deploy/keycloak/realm
    When the committed realm files are inspected
    Then no realm user should be present in the committed files
    And no client secret should be present in the committed files

  # Why: The identity service is tailnet-only — never reachable from the public internet
  @task:TASK-KC-006
  @negative @smoke
  Scenario: The identity service is not reachable from the public internet
    Given the identity service is running on the NAS
    When a connection to the issuer is attempted from outside the tailnet
    Then the identity service should be unreachable
    And no WAN port-forward at the edge gateway should route to it

  # Why: The password-grant test client must never exist in the production realm
  @task:TASK-KC-002
  @negative
  Scenario: The production realm does not contain the test-only live-suite client
    Given the production realm was imported from code
    When the production realm clients are listed
    Then the "live-suite" client should be absent from the production realm

  # Why: A plain-http issuer is unusable by native-app OIDC — the issuer must be https
  @task:TASK-KC-002
  @negative
  Scenario: A plain-http issuer is not accepted as the realm issuer
    Given the realm issuer was configured as plain http instead of the tailnet https name
    When a native app attempts OIDC discovery against it
    Then the discovery should be rejected as an untrusted issuer
    And the runbook should require the https tailnet issuer instead

  # ==========================================================================
  # GROUP D: Edge Cases
  # ==========================================================================

  # Why: Re-running standup must be safe — a realm re-import must not delete runbook-created users
  # [ASSUMPTION: confidence=medium] Realm import is non-overwriting on re-run, so runbook-created users survive
  @task:TASK-KC-005
  @edge-case @smoke
  Scenario: Re-running the standup re-imports the realm without deleting runbook-created users
    Given a user was created by the runbook after the initial realm import
    When the standup runbook is executed a second time
    Then the realm clients, roles, and claim mapper should still match the committed code
    And the previously runbook-created user should still exist

  # Why: KC-D2 fallback — if the DSM cert path fights, fall back to tailscale serve, same issuer name
  @task:TASK-KC-005
  @edge-case
  Scenario: The standup falls back to tailscale serve when the direct certificate mount fails on DSM
    Given the direct tailscale certificate mount fails on the NAS
    When the operator applies the documented fallback
    Then the identity service should be fronted by tailscale serve instead
    And the advertised realm issuer name should remain the same tailnet MagicDNS name

  # Why: After a NAS reboot the identity service and its realm state must survive unattended
  @task:TASK-KC-001
  @edge-case
  Scenario: The identity service and its realm survive a NAS reboot
    Given the identity service is running with its realm imported
    When the NAS is rebooted
    Then the identity service should restart automatically
    And the study-tutor realm with its clients, roles, and mapper should still be present

  # Why: If either database dump fails, the nightly backup must report failure, not mask it
  @task:TASK-KC-004
  @edge-case @negative
  Scenario: A failed keycloak dump makes the nightly backup report failure
    Given the nightly backup is running
    When the keycloak database dump fails
    Then the backup routine should exit with a failure
    And the failure should be surfaced to the operator rather than silently ignored

  # ==========================================================================
  # GROUP E: Security, Concurrency, Integrity, Integration (edge expansion)
  # ==========================================================================

  # Why: Two roles share one Postgres — the IdP role must not reach learner tables
  # [ASSUMPTION: confidence=medium] The keycloak role is a distinct non-superuser owning only the keycloak database
  @task:TASK-KC-003
  @edge-case @negative @security
  Scenario: The keycloak database role cannot read the learner tables
    Given the keycloak role and the study_tutor role live in the same Postgres container
    When the keycloak role attempts to read the study_tutor learner tables
    Then the access should be denied
    And the keycloak role should only reach its own keycloak database

  # Why: Admin bootstrap is a credential — it must not be committed and must not face the WAN
  @task:TASK-KC-006
  @edge-case @negative @security
  Scenario: The admin bootstrap credential is never committed and the admin console is tailnet-only
    Given the identity service was stood up with a bootstrap admin credential
    When the committed deploy files are inspected and the admin console is probed from outside the tailnet
    Then no admin credential should be present in the committed files
    And the admin console should be unreachable from the public internet

  # Why: A fat-fingered second run must not corrupt a live realm or double-bind the port
  @task:TASK-KC-005
  @edge-case
  Scenario: A second concurrent standup run does not corrupt the running realm
    Given a standup run has already brought the identity service up on its host port
    When a second standup run is started before the first has finished
    Then the second run should either no-op or fail cleanly on the already-bound resource
    And the running realm should remain intact and healthy

  # Why: The nightly dump must be point-in-time consistent even while the realm is being written
  @task:TASK-KC-004
  @edge-case
  Scenario: A nightly backup taken during realm writes is still consistent
    Given the identity service is actively writing realm state
    When the nightly keycloak dump runs at the same time
    Then the dump should capture a single point-in-time snapshot of the keycloak database
    And the dump should be restorable without corruption

  # Why: A ~90-day cert must renew unattended, or the issuer silently breaks for every device
  # [ASSUMPTION: confidence=medium] The tailscale cert is a ~90-day Let's Encrypt cert renewed automatically by tailscale
  @task:TASK-KC-005
  @edge-case
  Scenario: The tailscale certificate renews before expiry without a manual re-standup
    Given the mounted tailscale certificate is approaching its expiry
    When the renewal window is reached
    Then the certificate should be renewed automatically
    And the realm should continue to serve over trusted https without operator intervention

  # Why: A half-broken IdP is worse than a down one — it must fail fast when its store is absent
  @task:TASK-KC-001
  @edge-case @negative
  Scenario: The identity service fails fast when Postgres is unavailable at boot
    Given the study-tutor Postgres container is not available
    When the identity service is started
    Then it should fail to become healthy rather than come up half-configured
    And the operator should be pointed at the unavailable database as the cause

  # Why: The standup must not claim success if the TLS/issuer path could not be established
  @task:TASK-KC-005
  @edge-case @negative
  Scenario: The standup gate fails clearly when the certificate path is unavailable
    Given Tailscale or the certificate path is unavailable at standup time
    When the operator runs the standup gate
    Then the gate should fail with the missing certificate identified
    And the operator should be directed to the documented tailscale serve fallback
