# Generated by /feature-spec
# Feature: Keycloak Server-Side Token Validation (FEAT-AUTH-002, A2)
# Stack: python
# Assumptions: 7 (see keycloak-server-token-validation_assumptions.yaml)
# Generated: 2026-07-08T19:50:14Z
# Scope: FEAT-AUTH-002 A2 server only — the TokenResolver seam per design KC-D6.
#   resolve_student_from_token keeps its outer contract (Bearer extraction + the
#   unseeded-student guard, ASSUM-001 / binding §3) and delegates step 2 to an
#   injected resolver. TableTokenResolver stays in auth.py with byte-for-byte
#   current behaviour (the interim/degenerate default; hermetic suites keep it).
#   KeycloakTokenResolver lands in a NEW sibling module http/auth_keycloak.py
#   (PyJWT + PyJWKClient; validates signature, iss, aud, exp; extracts the
#   student_id claim per KC-D3; JWKS-URL override for the extra_hosts/IP-fetch
#   gotcha, KC-D2). STUDY_TUTOR_AUTH_MODE=table|keycloak selects the resolver;
#   keycloak mode fails fast at boot on incomplete OIDC config. The AC-005
#   tripwire is kept and re-scoped: auth.py stays JWT-free forever, the imports
#   live only in auth_keycloak.py. The WS upgrade path inherits the resolver
#   automatically (binding §2.1). The live contract suite mints tokens via the
#   dev-realm live-suite client (KC-D4).
# RESOLVED in assumption review (operator confirmed all defaults, 2026-07-08):
#   default mode = table when unset; student-claim name defaults to "student_id";
#   boot fail-fast = process exits (SystemExit) matching the DSN discipline;
#   required keycloak-mode settings = issuer + audience (JWKS URL optional,
#   derived from issuer when absent); JWKS cache = PyJWKClient default
#   (kid-rotation aware); a clock-skew leeway of 60s applies to exp and nbf; an
#   unknown STUDY_TUTOR_AUTH_MODE value fails fast at boot.
# Out of scope: A1 NAS standup / realm-as-code (FEAT-AUTH-001); A3 app OIDC
#   sign-in (KC-D7); A4 robot device-grant pairing (KC-D4); token refresh /
#   revocation sophistication (design §4); MCP/stdio surface auth (ADR-ARCH-008);
#   the frozen HTTP/WS contract itself (§3 / binding §3 unchanged — only the
#   derivation source changes); parent role/endpoints (KC-D5).
# REVIEW REQUIRED: 2 low-confidence assumptions (ASSUM-001 clock-skew leeway,
#   ASSUM-007 unknown-auth-mode handling) — confirmed at proposed defaults by the
#   operator; Coach verifies both against the design (KC-D6) before freeze.
# References: docs/design/keycloak-auth-user-management-design.md (KC-D1..D7);
#   docs/design/references/keycloak-validation-reference-lpa-poc.md (the proven
#   validation core + divergences); src/study_tutor/http/auth.py (the seam +
#   AC-005 tripwire in tests/unit/http/test_auth.py); docs/design/contracts/
#   API-session-http-binding.md (§2.1 WS auth, §3 derivation, §4.1 Unauthenticated).

@feat-auth-002 @keycloak @auth @token-validation @phase-2
Feature: Keycloak Server-Side Token Validation
  As the study-tutor API server
  I want to validate real Keycloak identity tokens and derive the student from a verified claim
  So that household devices authenticate against household-owned identity without the frozen contract changing

  Background:
    Given the study-tutor server resolves the caller's student by validating a Bearer token
    And the validation strategy is chosen by the STUDY_TUTOR_AUTH_MODE setting

  # ==========================================================================
  # GROUP A: Key Examples
  # ==========================================================================

  # Why: Table mode is the interim/degenerate default and must behave exactly as auth.py does today (KC-D6)
  @task:TASK-KCA2-002
  @key-example @smoke
  Scenario: In table mode a configured token identifies its student
    Given the server is running in table mode with the dev token table
    When a request arrives with lilymay's configured token
    Then the caller should be identified as lilymay
    And the identification should match the behaviour before Keycloak was introduced

  # Why: Core keycloak-mode path — a validly-signed household token yields the student from the verified claim
  @task:TASK-KCA2-003
  @key-example @smoke
  Scenario: In keycloak mode a valid identity token identifies the student from its verified claim
    Given the server is running in keycloak mode against the household realm
    And lilymay is seeded as an identity row
    When a request arrives with a validly-signed token carrying the student claim "lilymay"
    Then the caller should be identified as lilymay
    And the student should be taken from the verified token, never from the request body

  # Why: WS must not need its own auth — it inherits the shared resolver at upgrade time (binding §2.1)
  @task:TASK-KCA2-004
  @key-example
  Scenario: A streaming connection authenticates through the same resolver as the plain routes
    Given the server is running in keycloak mode against the household realm
    When a streaming connection is opened with a validly-signed token for lilymay
    Then the connection should be accepted and identified as lilymay
    And no auth mechanism separate from the plain routes should be required

  # Why: The outer auth contract (extraction + unseeded guard) is identical across modes — only step 2 changes
  @task:TASK-KCA2-002
  @key-example
  Scenario Outline: The Bearer extraction contract is identical in both modes
    Given the server is running in <mode> mode
    When a request arrives with no Authorization header
    Then the request should be rejected as unauthenticated

    Examples:
      | mode     |
      | table    |
      | keycloak |

  # ==========================================================================
  # GROUP B: Boundary Conditions
  # ==========================================================================

  # Why: Just-inside boundary — a token still within its lifetime (and within the allowed clock-skew) validates
  # [ASSUMPTION: confidence=low] A clock-skew leeway of 60s is allowed on expiry (operator-confirmed default)
  @task:TASK-KCA2-003
  @boundary
  Scenario: A token whose expiry has not yet passed is accepted
    Given the server is running in keycloak mode against the household realm
    When a request arrives with a validly-signed token that expires in the near future
    Then the caller should be identified from the token

  # Why: Just-outside boundary — a token past its expiry (beyond the allowed skew) is refused
  @task:TASK-KCA2-003
  @boundary @negative
  Scenario: A token whose expiry has passed is rejected
    Given the server is running in keycloak mode against the household realm
    When a request arrives with a validly-signed token whose expiry has already passed
    Then the request should be rejected as unauthenticated

  # Why: Just-inside boundary — keycloak mode with every required setting present boots normally
  @task:TASK-KCA2-004
  @boundary
  Scenario: Keycloak mode boots when the OIDC configuration is complete
    Given STUDY_TUTOR_AUTH_MODE is set to keycloak
    And the issuer and audience settings are both present
    When the server starts
    Then the server should start normally and validate tokens against the realm

  # Why: Just-outside boundary — a missing required setting must fail fast, not start half-configured (KC-D6)
  # [ASSUMPTION: confidence=medium] The required keycloak-mode settings are the issuer and the audience
  @task:TASK-KCA2-004
  @boundary @negative
  Scenario Outline: Keycloak mode refuses to start when a required OIDC setting is missing
    Given STUDY_TUTOR_AUTH_MODE is set to keycloak
    And the <missing> setting is absent
    When the server starts
    Then the server should fail fast at boot with a clear configuration error
    And the server should not begin serving requests

    Examples:
      | missing  |
      | issuer   |
      | audience |

  # ==========================================================================
  # GROUP C: Negative Cases
  # ==========================================================================

  # Why: A forged or wrongly-signed token must never authenticate
  @task:TASK-KCA2-003
  @negative
  Scenario: A token with an unrecognised signature is rejected
    Given the server is running in keycloak mode against the household realm
    When a request arrives with a token signed by a key the realm does not publish
    Then the request should be rejected as unauthenticated

  # Why: A token minted by a different issuer must not be honoured
  @task:TASK-KCA2-003
  @negative
  Scenario: A token from an unexpected issuer is rejected
    Given the server is running in keycloak mode against the household realm
    When a request arrives with a validly-signed token whose issuer is not the configured realm
    Then the request should be rejected as unauthenticated

  # Why: A token not intended for this server (wrong audience) must not be honoured
  @task:TASK-KCA2-003
  @negative
  Scenario: A token whose audience does not include this server is rejected
    Given the server is running in keycloak mode against the household realm
    When a request arrives with a validly-signed token addressed to a different audience
    Then the request should be rejected as unauthenticated

  # Why: A mis-provisioned identity (missing student claim) must be a clean auth failure, never a server error (KC-D3, ASSUM-001)
  @task:TASK-KCA2-003
  @negative
  Scenario: A valid token missing the student claim is rejected as unauthenticated
    Given the server is running in keycloak mode against the household realm
    When a request arrives with a validly-signed token that carries no student claim
    Then the request should be rejected as unauthenticated
    And the server should not raise an unexpected error

  # Why: The unseeded-student guard still runs in keycloak mode — a valid identity without a seed row is refused (ASSUM-001)
  @task:TASK-KCA2-004
  @negative
  Scenario: A valid token for an unseeded student is refused
    Given the server is running in keycloak mode against the household realm
    And the student "newcomer" has no seeded identity row
    When a request arrives with a validly-signed token carrying the student claim "newcomer"
    Then the request should be rejected as unauthenticated

  # Why: Bearer extraction is unchanged — a non-Bearer scheme is rejected the same way in both modes
  @task:TASK-KCA2-002
  @negative
  Scenario Outline: A non-Bearer Authorization header is rejected in both modes
    Given the server is running in <mode> mode
    When a request arrives with an Authorization header that does not use the Bearer scheme
    Then the request should be rejected as unauthenticated

    Examples:
      | mode     |
      | table    |
      | keycloak |

  # ==========================================================================
  # GROUP D: Edge Cases
  # ==========================================================================

  # Why: Signing keys rotate; a token signed with a freshly-rotated key must still validate (cache is rotation-aware)
  @task:TASK-KCA2-003
  @edge-case
  Scenario: A token signed with a newly-rotated signing key still validates
    Given the server is running in keycloak mode and has previously cached the realm's signing keys
    When the realm rotates its signing keys and a request arrives with a token signed by the new key
    Then the server should refresh its knowledge of the signing keys and identify the caller

  # Why: The extra_hosts gotcha — keys are fetched by tailnet address while the issuer stays pinned to the realm name (KC-D2)
  @task:TASK-KCA2-003
  @edge-case
  Scenario: Signing keys are fetched by tailnet address while the issuer stays pinned to the realm name
    Given the server is running in keycloak mode with the signing-key location overridden to the tailnet address
    And the configured issuer remains the realm's public name
    When a request arrives with a token issued under the realm's public name
    Then the server should validate the signature using the address-fetched keys and accept the token

  # Why: AC-005 tripwire re-scoped — the base auth module must stay free of JWT/Keycloak imports forever (KC-D6)
  @task:TASK-KCA2-005
  @edge-case @regression
  Scenario: The base auth module stays free of JWT and Keycloak imports
    Given the auth resolution layer is split into the base module and the keycloak module
    When the base auth module is inspected for identity-library imports
    Then no JWT or Keycloak imports should be present in the base module
    And those imports should live only in the keycloak module

  # Why: The dev-reset route and Keycloak validation must never be active together (dev flavour stays table, KC-D6)
  @task:TASK-KCA2-004
  @edge-case
  Scenario: The developer reset route and keycloak mode never coexist
    Given the developer reset route is only ever mounted in the dev flavour
    And the dev flavour runs in table mode
    When the server runs in keycloak mode
    Then the developer reset route should not be present

  # Why: The live contract suite must obtain real tokens the supported way — the dev-realm live-suite client (KC-D4)
  @task:TASK-KCA2-006
  @edge-case
  Scenario: The live contract suite mints tokens through the dev-realm live-suite client
    Given the dev realm exposes the live-suite client for test token issuance
    When the live contract suite needs a token for a test student
    Then it should obtain the token through the live-suite client
    And the hermetic test suites should stay in table mode and mint no real tokens

  # Why: Algorithm-confusion is the classic JWKS-validation attack — only the realm's asymmetric algorithm may verify a token
  @task:TASK-KCA2-003
  @edge-case @negative @security
  Scenario: A token using an unexpected signing algorithm is rejected
    Given the server is running in keycloak mode against the household realm
    When a request arrives with a token that declares no signature or a symmetric signing algorithm
    Then the request should be rejected as unauthenticated
    And only the realm's asymmetric signing algorithm should ever be accepted

  # Why: A token pointing at a key the realm never published must not validate, even if otherwise well-formed
  @task:TASK-KCA2-003
  @edge-case @negative @security
  Scenario: A token referencing an unknown signing key is rejected
    Given the server is running in keycloak mode against the household realm
    When a request arrives with a validly-formed token whose key identifier is not among the realm's published keys
    Then the request should be rejected as unauthenticated

  # Why: If key material is unreachable, auth must fail closed as unauthenticated, never as an unexpected server error
  @task:TASK-KCA2-003
  @edge-case @integration
  Scenario: When the realm's signing keys are unreachable tokens are refused cleanly
    Given the server is running in keycloak mode against the household realm
    And the realm's signing-key location cannot be reached
    When a request arrives with a token that would otherwise be valid
    Then the request should be refused as unauthenticated
    And the server should not raise an unexpected error

  # Why: A non-token Bearer value must be a clean auth failure in keycloak mode, matching table mode's posture
  @task:TASK-KCA2-003
  @edge-case @negative
  Scenario: A garbage Bearer value is refused as unauthenticated in keycloak mode
    Given the server is running in keycloak mode against the household realm
    When a request arrives with a Bearer value that is not a well-formed token
    Then the request should be rejected as unauthenticated
    And the server should not raise an unexpected error

  # Why: The first requests after boot race on the key fetch — the cache must serve both without a double failure
  @task:TASK-KCA2-003
  @edge-case @concurrency
  Scenario: Concurrent first requests after boot share a single signing-key fetch
    Given the server has just started in keycloak mode and has not yet fetched the realm's signing keys
    When two requests carrying valid tokens arrive at the same time
    Then both callers should be identified
    And the realm's signing keys should be fetched without both requests failing

  # Why: A token whose validity window has not yet begun must be refused, mirroring the expiry boundary
  # [ASSUMPTION: confidence=low] The same 60s clock-skew leeway applied to expiry is applied to the not-before window
  @task:TASK-KCA2-003
  @edge-case @negative @boundary
  Scenario: A token that is not yet valid is rejected
    Given the server is running in keycloak mode against the household realm
    When a request arrives with a validly-signed token whose validity begins in the future beyond the allowed skew
    Then the request should be rejected as unauthenticated
