# Generated by /feature-spec
# Feature: Flutter Keycloak Sign-In (FEAT-AUTH-003, A3)
# Stack: flutter
# Assumptions: 7 (see flutter-keycloak-sign-in_assumptions.yaml)
# Generated: 2026-07-08T20:41:54Z
# Scope: FEAT-AUTH-003 A3 app slice of the Keycloak auth rollout only (design KC-D7,
#   gate KC-G3) — a real KeycloakIdentityProvider implementing the unchanged 3-member
#   IdentityProvider port (sync currentPrincipal kept; adapter refreshes proactively in
#   the background; signIn attempts a silent refresh before the interactive browser flow);
#   flutter_appauth + flutter_secure_storage added as a deliberate zero-added-deps DoD
#   scope event; PKCE S256 public client with a custom-scheme redirect and offline_access
#   scope so the family device stays signed in; SignInScreen loading/failure/cancel states
#   plus a sign-out affordance; composeSessionApi's identity parameter de-typed from the
#   concrete FakeIdentityProvider to the port (the hermetic fake flavour keeps the concrete
#   fake for its introspection hook and is otherwise unchanged); and the existing
#   Unauthenticated -> routeToSignIn recovery preserved as the hard fallback.
# Out of scope: A1 standup (FEAT-AUTH-001); A2 server TokenResolver / auth_keycloak.py
#   validation (FEAT-AUTH-002); A4 robot device-grant pairing (FEAT-AUTH-004); parent-facing
#   UI (KC-D5, role reserved only); token-rotation hardening beyond appauth defaults (design
#   §4); the exact PKCE/JWKS wire mechanics (an IdP/library property, documented here as intent).
# REVIEW REQUIRED: 1 low-confidence assumption (ASSUM-003, the custom-scheme redirect URI) —
#   human-overridden to com.appmilla.studytutor:/oauth2redirect; the build must register the
#   identical value on the Keycloak study-tutor-app client AND in the Android/iOS app config.
# References: docs/design/keycloak-auth-user-management-design.md (KC-D4, KC-D7, gate KC-G3);
#   docs/research/ideas/keycloak-auth-scope-and-build-plan.md (FEAT-AUTH-003 decomposition);
#   app/lib/ports/identity_provider.dart (the 3-member port this adapter implements);
#   app/lib/ui/error_handling.dart (routeToSignIn / showConnectionProblem — the two treatments
#   the TransportError-vs-Unauthenticated distinction must keep separate);
#   app/lib/main.dart (composeSessionApi — the one composition seam that de-types to the port).

@feat-auth-003 @keycloak @app-signin @oidc
Feature: Flutter Keycloak Sign-In
  As a student signing in on the family device
  I want the app to sign me in through the household identity provider and keep me signed in
  So that I can start and resume tutoring sessions without repeatedly re-authenticating

  Background:
    Given the study-tutor app is installed on the family device
    And the app is running against the household Keycloak identity provider

  # ==========================================================================
  # GROUP A: Key Examples
  # ==========================================================================

  # Why: Core path — a first-time sign-in through the browser flow lands the student on home
  @task:TASK-KCA3-003
  @key-example @smoke
  Scenario: A first-time sign-in through the browser flow reaches the home screen
    Given no one is signed in on the device
    When I choose to sign in and complete authentication in the browser
    Then I should be signed in
    And I should land on the home screen ready to start a session

  # Why: The family device must stay signed in across restarts via the persisted offline session
  @task:TASK-KCA3-003
  @key-example @smoke
  Scenario: The device stays signed in across an app restart without a browser prompt
    Given I signed in earlier and then closed the app
    When I reopen the app
    Then I should still be signed in without seeing the browser sign-in
    And I should land on the home screen

  # Why: signIn attempts a silent refresh of the stored session before ever opening the browser
  @task:TASK-KCA3-003
  @key-example
  Scenario: Signing in reuses the stored session silently when it is still valid
    Given I have a still-valid stored session
    When I choose to sign in
    Then I should be signed in without the browser opening

  # Why: The new sign-out affordance clears the session and returns to sign-in
  # [ASSUMPTION: confidence=medium] Sign-out clears the local session only (secure store + currentPrincipal); it does not call the IdP end-session endpoint
  # [ASSUMPTION: confidence=medium] The sign-out affordance lives on the home screen (an app-bar action)
  @task:TASK-KCA3-005
  @key-example @smoke
  Scenario: Signing out clears the session and returns to the sign-in screen
    Given I am signed in on the home screen
    When I sign out
    Then I should no longer be signed in
    And I should be returned to the sign-in screen

  # Why: KC-G3 — a >5-minute idle must not interrupt an active session; background refresh keeps the token fresh
  # [ASSUMPTION: confidence=medium] The access-token lifetime is about 5 minutes (Keycloak default; KC-G3 tests a >5-minute idle)
  # [ASSUMPTION: confidence=high] The adapter refreshes proactively before expiry, driven by the appauth token-response expiry (KC-D7)
  @task:TASK-KCA3-003
  @key-example @smoke
  Scenario: An active session survives an idle period longer than the access-token lifetime
    Given I am signed in with an active session
    When the app sits idle for longer than the access-token lifetime and I then continue the session
    Then the session should continue without a re-sign-in prompt

  # Why: The composeSessionApi de-type to the port must not disturb the hermetic fake flavour
  @task:TASK-KCA3-006
  @key-example @smoke @regression
  Scenario: The hermetic fake flavour still signs in with no browser and no network
    Given the app is instead built in the hermetic fake flavour with no backend configured
    When I sign in
    Then I should be signed in against the in-process fake with no browser and no network call

  # ==========================================================================
  # GROUP B: Boundary Conditions
  # ==========================================================================

  # Why: Just-inside boundary — an idle shorter than the offline-session window still refreshes silently
  # [ASSUMPTION: confidence=high] The offline-session idle limit is 30 days (KC-D4: offline idle default 30 days, refresh at least monthly)
  @task:TASK-KCA3-003
  @boundary
  Scenario: A device idle just under the offline-session window refreshes without a browser
    Given I have not opened the app for just under 30 days
    When I reopen the app
    Then I should still be signed in without the browser sign-in

  # Why: Just-outside boundary — past the offline-session window the stored session is dead and the browser is required
  # [ASSUMPTION: confidence=high] The offline-session idle limit is 30 days (KC-D4)
  @task:TASK-KCA3-003
  @boundary @negative
  Scenario: A device idle beyond the offline-session window requires an interactive sign-in
    Given I have not opened the app for more than 30 days
    When I reopen the app and choose to sign in
    Then the silent refresh should fail and the browser sign-in should be required

  # Why: Across the idle band below the offline limit, background refresh keeps the session usable
  # [ASSUMPTION: confidence=medium] 6 minutes sits just past the ~5-minute access-token life; 29 days sits just under the 30-day offline limit
  @task:TASK-KCA3-003
  @boundary
  Scenario Outline: Sessions remain usable across idle periods within the offline window
    Given I am signed in and the app has been idle for <idle>
    When I continue an active session
    Then the session should continue without a re-sign-in prompt

    Examples:
      | idle      |
      | 6 minutes |
      | 1 day     |
      | 29 days   |

  # ==========================================================================
  # GROUP C: Negative Cases
  # ==========================================================================

  # Why: The cancel state — the student backs out of the browser without authenticating
  @task:TASK-KCA3-004
  @negative @smoke
  Scenario: Cancelling the browser sign-in returns to the sign-in screen signed out
    Given no one is signed in on the device
    When I start signing in and cancel the browser without authenticating
    Then I should remain signed out
    And the sign-in screen should show that sign-in was cancelled

  # Why: The failure state — the identity provider errors or is unreachable during sign-in
  # [ASSUMPTION: confidence=medium] The failure state offers a manual "try again"; there is no automatic retry
  @task:TASK-KCA3-004
  @negative @smoke
  Scenario: A failed sign-in shows a failure state and lets me try again
    Given the household identity provider cannot be reached
    When I choose to sign in
    Then the sign-in should fail
    And the sign-in screen should show a failure state offering to try again

  # Why: The preserved hard fallback — a backend-rejected token routes the student back to sign-in
  @task:TASK-KCA3-006
  @negative @smoke @regression
  Scenario: A backend-rejected token routes the student back to sign-in
    Given I am signed in and using the app
    When the backend rejects my token as no longer valid
    Then I should be returned to the sign-in screen to sign in again

  # Why: A valid IdP login for an unprovisioned identity still cannot use the app — it lands back at sign-in
  @task:TASK-KCA3-006
  @negative
  Scenario: Signing in as an identity with no provisioned student returns to sign-in
    Given I can authenticate at the identity provider but my identity has no provisioned student
    When I complete the browser sign-in and take my first action
    Then that action should be rejected as unauthorised
    And I should be returned to the sign-in screen

  # ==========================================================================
  # GROUP D: Edge Cases
  # ==========================================================================

  # Why: While the browser flow runs the screen shows loading and a second tap cannot start a duplicate flow
  @task:TASK-KCA3-004
  @edge-case
  Scenario: A second sign-in tap during an in-progress sign-in is ignored
    Given no one is signed in on the device
    And a browser sign-in is already in progress showing the loading state
    When I tap sign in again
    Then only one sign-in flow should be running

  # Why: The custom-scheme redirect must complete even though the browser backgrounded the app
  @task:TASK-KCA3-003
  @edge-case
  Scenario: A sign-in completes after the browser redirects back into the app
    Given I am authenticating in the external browser
    When the browser redirects back to the app and the app returns to the foreground
    Then the sign-in should complete and I should be signed in

  # Why: The silent-then-interactive path lets the hard-fallback loop recover without a browser when the offline token is still good
  @task:TASK-KCA3-003
  @edge-case @regression
  Scenario: Re-signing in after a rejected token recovers silently when the stored session is still refreshable
    Given my token was rejected and I was returned to sign-in
    And my stored offline session can still be refreshed
    When I choose to sign in again
    Then I should be signed back in without the browser opening

  # Why: A failed background refresh must degrade gracefully to the sign-in fallback, never crash
  @task:TASK-KCA3-003
  @edge-case @negative
  Scenario: A failed background refresh degrades to the sign-in fallback rather than crashing
    Given I am signed in and the background refresh can no longer reach the identity provider
    When the stored session can no longer be refreshed and I next use the app
    Then I should be returned to the sign-in screen
    And the app should not crash or hang

  # Why: If the stored session cannot be read, the app must present sign-in, not fail to launch
  @task:TASK-KCA3-002
  @edge-case @negative
  Scenario: An unreadable stored session is treated as signed out
    Given the securely stored session cannot be read at launch
    When I open the app
    Then I should be shown the sign-in screen
    And the app should start normally rather than fail to launch

  # Why: The two new sign-in dependencies are a deliberate, recorded break from the zero-added-deps DoD
  @task:TASK-KCA3-001
  @edge-case @regression
  Scenario: The new sign-in dependencies are recorded as a deliberate scope event
    Given the app previously declared a zero-added-runtime-dependencies definition of done
    When the sign-in feature adds its identity and secure-storage dependencies
    Then exactly those two runtime dependencies should be added
    And the addition should be recorded as a deliberate scope event

  # ==========================================================================
  # GROUP E: Security, Concurrency, Integration (edge expansion)
  # ==========================================================================

  # Why: PKCE S256 binds the code to this device so an intercepted authorization code cannot be redeemed
  @task:TASK-KCA3-003
  @edge-case @security
  Scenario: An intercepted authorization code cannot be exchanged for a session
    Given I am completing a browser sign-in
    When the authorization code is intercepted and replayed from another device
    Then the exchange should be rejected
    And no session should be issued to the interceptor

  # Why: A minor's session on a shared family device must live in the platform secure store, not plaintext
  @task:TASK-KCA3-002
  @edge-case @security
  Scenario: The signed-in session is held in the platform secure store
    Given I am signed in on the device
    When the app's on-device storage is inspected
    Then my session credentials should be held in the platform secure store
    And they should not be readable as plaintext by another app

  # Why: Only the app's own custom-scheme redirect may deliver the result — a foreign redirect cannot inject a session
  # [ASSUMPTION: confidence=low] The app's custom-scheme redirect URI is com.appmilla.studytutor:/oauth2redirect (human-overridden; must match the Keycloak client registration and the Android/iOS app config)
  @task:TASK-KCA3-003
  @edge-case @security
  Scenario: A redirect to a scheme other than the app's own is not honoured
    Given a sign-in result is delivered to a redirect that is not the app's own custom scheme
    When the app processes the redirect
    Then the foreign redirect should be ignored
    And no session should be established from it

  # Why: Sign-out must win over an in-flight background refresh — no resurrection of a cleared session
  @task:TASK-KCA3-003
  @edge-case @security
  Scenario: Signing out during a background refresh leaves me signed out
    Given a background refresh is in flight
    When I sign out before the refresh completes
    Then I should remain signed out
    And the completing refresh should not restore my session

  # Why: A missing discovery document at sign-in is a failure, not a cancel — the states must not be conflated
  @task:TASK-KCA3-004
  @edge-case @negative
  Scenario: An unavailable identity-provider discovery at sign-in shows the failure state
    Given no one is signed in on the device
    And the identity provider's discovery document cannot be retrieved
    When I choose to sign in
    Then the sign-in should fail with the failure state, not the cancel state
    And I should be offered the chance to try again

  # Why: A dead backend is a connection problem, not an auth failure — it must not route a signed-in student to sign-in
  @task:TASK-KCA3-006
  @edge-case @negative @regression
  Scenario: A backend unreachable after sign-in shows a connection problem rather than routing to sign-in
    Given I am signed in and the backend has become unreachable
    When I try to start or resume a session
    Then I should see a connection problem and stay where I am
    And I should not be routed back to the sign-in screen
