# Generated by /feature-spec
# Feature: Streaming tutoring turns — live text and voice on the session channel (FEAT-VOICE-002)
# Stack: python (Starlette HTTP adapter, WS transport)
# Assumptions: 10 (see streaming-voice_assumptions.yaml — all owner-confirmed 2026-07-06)
# Generated: 2026-07-06T20:32:40+01:00
#
# Companion features: voice-server-module (FEAT-VOICE-001) covers the non-streaming
# HTTP voice turn and its upload-validation boundary pairs; this spec covers the
# streaming path (frozen contract §7 Rev 1) and deliberately does not duplicate them.

@voice @feat-voice-002
Feature: Streaming tutoring turns — live text and voice on the session channel
  As a student in a tutoring session
  I want the tutor's answer to appear and be spoken while it is still being composed
  So that I start reading and hearing the answer within seconds instead of waiting for the whole reply

  Background:
    Given I am signed in as a student with an active tutoring session

  # ── Key examples ──────────────────────────────────────────────────────

  # Why: The core streaming promise — perceived latency becomes time-to-first-fragment, not full generation
  @task:TASK-VS2-001
  @key-example @smoke
  Scenario: A typed question's answer streams while it is still being composed
    Given I have opened the live channel for my session
    When I ask a typed question requesting a streamed answer
    Then the answer text arrives incrementally while the tutor is still composing it
    And the first fragment arrives before the full answer exists
    And the stream ends by confirming the turn is complete with its place in the session history

  # Why: The full voice frame flow in contract order — transcript first, then text, then spoken sentences
  @task:TASK-VS2-006
  @key-example @smoke
  Scenario: A spoken question streams a transcript, then answer text, then spoken sentences
    Given I have opened the live channel for my session
    When I send a spoken question over the live channel
    Then the transcript of my recording is confirmed back to me before anything else
    And the answer text arrives incrementally
    And each spoken sentence of the answer is announced as soon as it is ready to play
    And the stream ends by confirming the turn is complete

  # Why: Chunk-by-URL delivery — announced references must resolve to playable, ordered speech
  @task:TASK-VS2-007
  @key-example
  Scenario: Announced spoken chunks are playable and reproduce the answer in order
    Given a streamed voice answer announced several spoken sentence chunks
    When I fetch each announced chunk
    Then each fetch returns playable speech audio
    And playing the chunks in their announced order reproduces the spoken answer

  # Why: Streaming must not weaken per-turn durability — cross-device resume is a frozen contract property
  @task:TASK-VS2-003
  @key-example
  Scenario: A streamed turn is recorded in the session history exactly like a plain turn
    Given I have opened the live channel for my session
    When a streamed turn completes
    Then my question and the tutor's full assembled answer appear in the session history
    And resuming the session on another device shows the completed exchange

  # Why: The whole-answer path is a frozen contract commitment for clients that don't stream
  @task:TASK-VS2-005
  @key-example @regression
  Scenario: Asking without streaming still returns the whole answer in one response
    When I ask a question without requesting a streamed answer
    Then I receive the complete answer in a single response exactly as before

  # Why: ADR-ARCH-026 — the quality monitor is asynchronous; streaming must never wait on it
  @task:TASK-VS2-003
  @key-example
  Scenario: Streaming never waits for the tutor's quality review
    Given I have opened the live channel for my session
    When I ask a typed question requesting a streamed answer
    Then the answer begins streaming without waiting for the quality review
    And the quality review still takes place on the complete answer after the stream finishes

  # Why: ADR-ARCH-027 — never show or speak an unverified quote; verification gates each sentence chunk
  @task:TASK-VS2-002
  @key-example @smoke
  Scenario: An unverifiable quotation is corrected before it is shown or spoken
    Given the tutor's answer would include a quotation that cannot be verified against the study text
    When the answer streams
    Then the sentence containing the quotation is corrected or annotated before its text is shown
    And the spoken audio for that sentence is produced only from the corrected text

  # ── Boundary conditions ───────────────────────────────────────────────

  # Why: Just-inside the chunking floor — a short answer must not be fragmented or dropped
  @task:TASK-VS2-002
  @boundary
  Scenario: A short answer is spoken as a single chunk
    Given the tutor's answer is shorter than one sentence-chunk's worth of words
    When the answer streams
    Then exactly one spoken chunk is announced and it covers the whole answer

  # [ASSUMPTION: confidence=high] Chunks target roughly 15-25 words at sentence boundaries (design §5.3 pin)
  # Why: The chunking discipline — breaks only at sentence boundaries, near the pinned size
  @task:TASK-VS2-002
  @boundary
  Scenario: A long answer is spoken in complete-sentence chunks of roughly the pinned size
    Given the tutor's answer runs to many sentences
    When the answer streams
    Then the answer is spoken in multiple chunks announced in order
    And every chunk break falls on a sentence boundary
    And each chunk is roughly the pinned chunk size in length

  # Why: ADR-ARCH-027's named obligation — the verifier sees accumulated text, not isolated chunks
  @task:TASK-VS2-002
  @boundary
  Scenario: A quotation straddling a chunk boundary is still verified as one quotation
    Given the tutor's answer contains a quotation that spans two sentence chunks
    When the answer streams
    Then the quotation is verified against the accumulated answer text rather than each chunk alone
    And no part of the quotation is shown or spoken before that verification completes

  # Why: Just-inside boundary — the recording caps apply on the live channel exactly as on a plain voice turn
  @task:TASK-VS2-006
  @boundary
  Scenario: A recording at exactly the size cap is accepted over the live channel
    Given I have a recording of exactly the maximum allowed size
    When I send it as a spoken question over the live channel
    Then the turn proceeds and the transcript is confirmed back to me

  # [ASSUMPTION: confidence=low] A refused recording leaves the channel open for an immediate retry
  # Why: Just-outside boundary — refusal must match the plain voice turn and not cost the connection
  @task:TASK-VS2-006
  @boundary @negative
  Scenario: A recording just over the size cap is refused and the channel stays usable
    Given I have a recording just over the maximum allowed size
    When I send it as a spoken question over the live channel
    Then it is refused as too large with the same reason a plain voice turn gives
    And I can send another question on the same channel straight away

  # ── Negative cases ────────────────────────────────────────────────────

  # Why: The channel is bearer-guarded at connection time — nothing streams to an unauthenticated caller
  @task:TASK-VS2-004
  @negative
  Scenario: Opening the live channel without valid credentials is refused
    When the live channel for my session is opened without valid credentials
    Then the connection is refused as unauthenticated
    And no answer text or audio is ever delivered on it

  # Why: Ownership is checked at connection time — sessions are private to their student
  @task:TASK-VS2-004
  @negative
  Scenario: Another student cannot open my session's live channel
    Given another student is signed in
    When that student tries to open the live channel for my session
    Then the connection is refused as forbidden

  # Why: Session lifecycle rules are transport-independent
  @task:TASK-VS2-004
  @negative
  Scenario: Streaming a turn on an ended session is refused
    Given my session has ended
    When I ask a streamed question on its live channel
    Then the request is refused because the session has ended

  # Why: Unknown sessions are refused identically on every surface
  @task:TASK-VS2-004
  @negative
  Scenario: The live channel for an unknown session is refused as not found
    When the live channel is opened for a session that does not exist
    Then the connection is refused as not found

  # Why: Degradation is a feature with copy — voice loss must never take text streaming down with it
  @task:TASK-VS2-006
  @negative
  Scenario: When speech services are down, voice is refused but typed streaming still works
    Given the speech services are unavailable
    When I send a spoken question over the live channel
    Then it is refused because spoken answers are unavailable
    And a typed streamed question on the same channel still succeeds

  # Why: One validation rulebook — channel refusals must match the plain voice turn (specced in FEAT-VOICE-001)
  @task:TASK-VS2-006
  @negative
  Scenario Outline: Invalid recordings over the live channel are refused for the same reasons as a plain voice turn
    Given I have <recording>
    When I send it as a spoken question over the live channel
    Then it is refused because <reason>

    Examples:
      | recording                            | reason                      |
      | a recording in an unsupported format | the format is not supported |
      | a recording that contains no data    | the recording is empty      |
      | a recording of silence               | it could not be understood  |

  # [ASSUMPTION: confidence=medium] The live channel is mounted with the voice routes, so the voice flag gates it entirely
  # Why: Flag-off must look like the feature never existed, without touching plain tutoring
  @task:TASK-VS2-004
  @negative
  Scenario: With the voice feature disabled, the live channel is absent and plain tutoring is unaffected
    Given the voice feature has been disabled
    When I try to open the live channel for my session
    Then it is refused as if the channel never existed
    And asking a question without streaming still succeeds

  # ── Edge cases ────────────────────────────────────────────────────────

  # [ASSUMPTION: confidence=medium] A failed stream records no tutor answer; no partial text persists as an exchange
  # Why: A half-generated answer must never masquerade as a completed exchange
  @task:TASK-VS2-003
  @edge-case
  Scenario: Answer generation fails partway through streaming
    Given I have opened the live channel for my session
    And answer generation will fail partway through
    When I ask a typed question requesting a streamed answer
    Then I am told the turn failed
    And no completed exchange for it appears in the session history
    And I can ask the question again

  # [ASSUMPTION: confidence=low] The server finishes the turn after a disconnect so the exchange survives for resume
  # Why: Cross-device durability — losing WiFi mid-answer should not lose the turn
  @task:TASK-VS2-003
  @edge-case
  Scenario: My connection drops while an answer is streaming
    Given a streamed answer to my question is underway
    When my connection to the live channel drops
    Then the turn still completes and is recorded in the session history
    And resuming the session later shows the full exchange

  # [ASSUMPTION: confidence=medium] Streaming analogue of the owner-confirmed FEAT-VOICE-001 ASSUM-005
  # Why: Speech is an enhancement — losing it mid-answer must not cost the text or the turn
  @task:TASK-VS2-007
  @edge-case
  Scenario: Speech synthesis fails partway through a spoken answer
    Given speech synthesis will fail after the first spoken chunk
    When I send a spoken question over the live channel
    Then the answer text continues streaming to completion
    And no further spoken chunks are announced after the failure
    And the turn completes and is recorded normally

  # [ASSUMPTION: confidence=low] Verification failure fails closed — the turn errors rather than emit unverified content
  # Why: The D3 principle under failure — never show or speak content whose quotes could not be checked
  @task:TASK-VS2-002
  @edge-case
  Scenario: Quote verification cannot complete for a sentence
    Given quote verification will fail while an answer is streaming
    When the answer reaches the affected sentence
    Then that sentence is neither shown nor spoken unverified
    And I am told the turn could not be completed

  # [ASSUMPTION: confidence=low] Questions on one channel are handled one at a time, in order
  # Why: Concurrency on a single channel needs defined ordering, not interleaved streams
  @task:TASK-VS2-004
  @edge-case
  Scenario: A second question sent while an answer is still streaming
    Given a streamed answer to my first question is underway
    When I send a second question on the same channel
    Then each question is answered one at a time in the order asked
    And the two answers are never interleaved

  # Why: The declared size on the channel is a claim, not the enforcement — mirrors the W1 true-size defence
  @task:TASK-VS2-006
  @edge-case @negative
  Scenario: A recording larger than its declared size is judged on what was actually sent
    Given I declare a small recording but send more data than declared
    When I send it as a spoken question over the live channel
    Then acceptance is decided on the size actually received, not the declared size

  # ── Security, concurrency, and integration boundaries ────────────────

  # Why: Announced chunk references are not capabilities — ownership is enforced on every fetch
  @task:TASK-VS2-008
  @edge-case @negative
  Scenario: Another student cannot fetch my announced spoken chunks
    Given a streamed voice answer announced spoken sentence chunks in my session
    And another student is signed in
    When that student tries to fetch one of my announced chunks
    Then the fetch is refused as forbidden

  # Why: Chunk references are scoped to the session that produced them
  @task:TASK-VS2-008
  @edge-case @negative
  Scenario: An announced chunk reference is valid only within its own session
    Given a streamed voice answer announced spoken sentence chunks in my session
    And I also have a second session
    When I try to fetch one of those chunks through the second session
    Then the fetch is refused as not found

  # Why: The two-device durable-sessions promise must hold under streaming — ordered, never interleaved
  @task:TASK-VS2-004
  @edge-case
  Scenario: Questions from two of my devices on the same session are answered one at a time
    Given I have opened the live channel for my session on two devices
    When each device asks a question at the same time
    Then the questions are answered one at a time in the order received
    And both completed exchanges appear in the shared session history in order

  # Why: Concurrent channels must be fully isolated — no cross-talk of text or audio references
  @task:TASK-VS2-004
  @edge-case
  Scenario: Two students streaming at the same time see only their own answers
    Given another student is streaming a turn in their own session
    When I ask a streamed question in my session at the same time
    Then I receive only the fragments and spoken chunks of my own answer
    And the other student receives only theirs

  # [ASSUMPTION: confidence=low] The stall bound is the existing model request timeout; no new per-fragment timeout
  # Why: A silent hang is worse than a failure — the wait is bounded
  @task:TASK-VS2-001
  @edge-case
  Scenario: A tutor model that stalls without producing anything ends in a visible failure
    Given the tutor model will stall and produce nothing
    When I ask a typed question requesting a streamed answer
    Then the turn fails visibly after a bounded wait rather than hanging indefinitely
    And I can ask again

  # [ASSUMPTION: confidence=low] Eviction never touches an unplayed, unexpired chunk of a maximum-length answer
  # Why: Bounded memory must not cost playback — orderly fetching always finds its chunk
  @task:TASK-VS2-008
  @edge-case
  Scenario: A very long spoken answer does not lose chunks before they can be played
    Given the tutor's answer is long enough to produce many spoken chunks
    When I fetch each chunk in announced order as playback proceeds
    Then every announced chunk is still available when its turn to play arrives
