# Generated by /feature-spec
# Feature: Reachy Local Voice Migration (FEAT-VOICE-004)
# Stack: python
# Assumptions: 9 (see reachy-local-voice-migration_assumptions.yaml)
# Generated: 2026-07-07

@reachy-voice
Feature: Reachy Local Voice Migration
  As the parent of a minor using the Reachy tutor robot
  I want the robot's voice conversation to run entirely on our local GB10, going direct to the study-tutor
  So that my child's voice never transits a third-party cloud and the robot shares one continuous tutoring session with the phone

  Background:
    Given the local voice server is running on the GB10
    And the robot is re-pointed to the local voice server
    And the study-tutor is reachable on the local network

  # ── GROUP A: Key Examples ──────────────────────────────────────────

  # Why: The whole point of the migration — closes the D3 cloud-audio exception for a minor
  @key-example @smoke
  Scenario: An open-mic conversation runs entirely on the local voice server
    Given the robot is listening on the open microphone
    When the student speaks to the robot
    Then the robot should reply using the local voice server
    And no speech-to-speech session should be established with the hosted cloud service

  # Why: Core tutoring path — robot reaches the study-tutor directly, not via Jarvis
  # [ASSUMPTION: confidence=high] Robot voice is Ryan — one voice across robot, app, and LPA
  @key-example @smoke
  Scenario: A spoken tutoring question is answered by the study-tutor in the robot's voice
    Given the student is in a tutoring conversation with the robot
    When the student asks the robot a tutoring question
    Then the robot should obtain the answer from the study-tutor
    And the robot should speak the answer in the configured robot voice
    And the fleet assistant should not be consulted for the tutoring turn

  # Why: D8 cross-device pickup — the reason ask_tutor goes over HTTP with identical session semantics
  # [ASSUMPTION: confidence=high] The shared default subject is "english" — resolved 2026-07-07 (ASSUM-001): matches the tutor fine-tune, the Scholar persona, and query_student_model; the app default moved 'maths'->'english'
  @key-example
  Scenario: The robot resumes a tutoring session the student started on the phone
    Given the student has an active tutoring session started on the phone for the shared subject
    When the student asks the robot a question in that subject
    Then the robot should resume the same tutoring session rather than start a new one
    And the conversation history should continue unbroken across phone and robot

  # Why: R-G3, the highest-risk unknown — tool calls must round-trip through the local session
  @key-example @smoke
  Scenario: A student-model tool call round-trips through the local voice session
    Given the student is talking to the robot through the local voice server
    When a turn triggers a lookup of what the student already knows
    Then the student-model lookup should complete through the local session
    And the robot should narrate the result of that lookup

  # Why: D2 — the tool's data plane moved off the frozen graph to the durable store
  @key-example
  Scenario: The student-model lookup reads from the durable student store
    Given the student's learning record lives in the durable student store
    When the robot looks up what the student already knows
    Then the result should reflect the student's current durable record
    And no reading should come from the retired knowledge graph

  # Why: Jarvis-out-of-the-loop boundary — simple chat must not pay the tutor round-trip
  @key-example
  Scenario: A simple conversational remark stays on the local voice server
    Given the student is chatting with the robot about something other than tutoring
    When the student makes a simple conversational remark
    Then the robot should answer directly from the local voice server
    And neither the study-tutor nor the fleet assistant should be consulted

  # ── GROUP B: Boundary Conditions ───────────────────────────────────

  # Why: D6/D8 — resume matches on (student, subject); the subject string is the exact boundary
  # [ASSUMPTION: confidence=high] resume_if_active matches on (student, subject), and an omitted subject defaults to an empty string
  @boundary
  Scenario Outline: A phone session is resumed only when the robot sends the exact shared subject
    Given the student has an active phone session for subject "<phone_subject>"
    When the robot sends a tutoring turn for subject "<robot_subject>"
    Then the robot turn should <outcome>

    Examples:
      | phone_subject | robot_subject | outcome                                |
      | english       | english       | resume the existing session            |
      | english       | maths         | start a separate session               |
      | english       |               | start a separate empty-subject session |

  # Why: R-G5 residency — warm resident set vs cold model load is the latency boundary the owner priced
  # [ASSUMPTION: confidence=high] The tutor model set is the GB10 standing default with a raised keep-alive (R-G5, decided 2026-07-05)
  @boundary
  Scenario Outline: Tutoring-turn responsiveness depends on the tutor model's residency
    Given the tutor model set is "<residency>"
    When the student asks the robot a tutoring question
    Then the robot should still return the correct answer
    And the response time should be "<expectation>"

    Examples:
      | residency                | expectation                      |
      | resident and warm        | within the conversational budget |
      | idle past its keep-alive | delayed by a one-off cold load   |

  # Why: R-G2 checkpoint gate — the voice pin must hold whichever TTS checkpoint is accepted
  # [ASSUMPTION: confidence=medium] The s2s unit loads the Qwen3-TTS 0.6B pin, with 1.7B as an owner-decided fallback (R-G2 gate)
  @boundary
  Scenario: The robot speaks in the configured voice regardless of which TTS checkpoint loads
    Given the local voice server has loaded its text-to-speech model
    When the robot speaks any reply
    Then the reply should use the configured robot voice

  # ── GROUP C: Negative Cases ────────────────────────────────────────

  # Why: Graceful degradation — the study-tutor being down must not break the robot conversation
  # [ASSUMPTION: confidence=low] On study-tutor unavailability the robot speaks a brief "the tutor isn't available right now" message; exact persona copy is unspecified
  @negative
  Scenario: The robot degrades gracefully when the study-tutor is unreachable
    Given the study-tutor is not reachable
    When the student asks the robot a tutoring question
    Then the robot should speak a brief unavailable message
    And the open-mic conversation should continue afterwards

  # Why: D3 closure has no cloud failover by design — fail closed, never egress a minor's voice
  @negative
  Scenario: The robot never falls back to the cloud when the local voice server is down
    Given the local voice server is not running
    When the student speaks to the robot
    Then no speech-to-speech session should be established with the hosted cloud service
    And the student's speech should never leave the local network

  # Why: D1 — a tool with the rejected interface shape must not load or fire
  @negative
  Scenario: A tool that does not conform to the required tool interface is not offered to the robot
    Given a tool defined with the outdated interface shape
    When the robot's tools are loaded
    Then that tool should not be available to the robot
    And no turn should attempt to call it

  # Why: D6 trap made explicit — omitting the subject silently defeats pickup
  @negative
  Scenario: A tutoring turn that omits the subject does not resume the phone session
    Given the student has an active phone session for the shared subject
    When the robot sends a tutoring turn with no subject
    Then the robot turn should not resume the phone session
    And a separate session should be created instead

  # ── GROUP D: Edge Cases ────────────────────────────────────────────

  # Why: R-G6 two-robot fleet fact — the pipeline is single-conversation-shaped
  # [ASSUMPTION: confidence=medium] Both robots share one s2s server; one instance per robot is the priced fallback (R-G6)
  @edge-case
  Scenario: Two robots hold tutoring conversations at the same time
    Given both household robots are re-pointed to the local voice serving
    When each robot holds a conversation at the same time
    Then each robot should carry its own conversation without disrupting the other

  # Why: Known W0-R defect — tool-call control text was being spoken aloud
  @edge-case
  Scenario: Tool-call control text is not spoken aloud
    Given a turn that triggers a tool call
    When the robot narrates the turn
    Then the robot should speak only the conversational answer
    And the tool-call control text should not be spoken

  # Why: Ephemeral-audio invariant — no raw voice at rest anywhere
  # [ASSUMPTION: confidence=high] No raw audio persists on the robot or the GB10; only the transcript persists, in the tutor's session store (design §5.6, AC-R3)
  @edge-case
  Scenario: No raw audio is retained after a conversation
    Given the student has finished a conversation with the robot
    When the robot and GB10 storage are inspected
    Then no raw audio recording should be found at rest
    And only the conversation transcript should exist in the tutor's session store

  # Why: D3 recon — the installed Pi app version may not support the re-point keys
  @edge-case
  Scenario: Migration is blocked when the robot's installed app cannot honour the re-point
    Given the robot's installed conversation app does not support the local re-point setting
    When the migration is applied to that robot
    Then the robot should not silently keep using the cloud
    And the migration should require the app to be upgraded first

  # Why: D7 — the Pi clone is hand-edited; a plain pull would conflict
  @edge-case
  Scenario: Shipping the new tutor tool to the robot preserves the robot's local configuration
    Given the robot's on-device app carries hand-applied local settings
    When the new tutor tool is deployed to the robot
    Then the robot's hand-applied local settings should still be in effect
    And the deployment should not have relied on merging over the hand-edited files

  # Why: D4 — reconcile repo-vs-Pi profile drift to the Pi where the Pi is right
  @edge-case
  Scenario: The reconciled robot profile keeps the working tool set the robot already runs
    Given the robot already runs without the tool known to be broken in its app version
    When the robot profile is reconciled
    Then the known-broken tool should remain absent
    And the tools the robot actually relies on should remain present

  # Why: The robot must not be able to reach the tutor as anyone but the intended student
  @edge-case @negative
  Scenario: The robot can only act within its own student's tutoring sessions
    Given the robot is configured for its assigned student
    When the robot sends a tutoring turn
    Then the turn should act only on that student's session
    And it should not be able to reach another student's session

  # ── Expansion: security, concurrency, integration ──────────────────

  # Why: The robot authenticates to the tutor as a bearer client — a bad token must not leak as content
  @edge-case @negative
  Scenario: The robot degrades gracefully when the study-tutor rejects its credentials
    Given the robot's tutoring credential is not accepted by the study-tutor
    When the student asks the robot a tutoring question
    Then the robot should speak a brief unavailable message
    And the credential failure should not be spoken as if it were tutoring content
    And the open-mic conversation should continue afterwards

  # Why: A minor may say anything into the mic; spoken text must never become a command/tool trigger
  @edge-case @negative
  Scenario: Command-like speech is treated as ordinary tutoring input
    Given the student is in a tutoring conversation with the robot
    When the student speaks a question containing command-like or tool-like phrasing
    Then the phrasing should be treated as ordinary spoken question content
    And it should not cause any tool to run outside the normal tutoring flow

  # Why: D8 pickup means phone and robot can both hold the one resumed session at once — the race
  @edge-case
  Scenario: Simultaneous phone and robot turns on the resumed session are handled cleanly
    Given the phone and the robot are both attached to the same resumed tutoring session
    When a turn is sent from the phone and from the robot at nearly the same time
    Then both turns should be recorded against the session in a consistent order
    And no turn should be lost or interleaved into another turn

  # Why: The tutor's cold-load can exceed the robot's open-mic patience — filler, not silent timeout
  # [ASSUMPTION: confidence=low] The persona speaks a "let me think about that…" acknowledgement to cover the ~5s+ tutor turn; exact filler copy is unspecified
  @edge-case
  Scenario: The robot covers a slow tutor answer conversationally instead of timing out silently
    Given a tutoring turn will take longer than a simple conversational reply
    When the student asks the robot a tutoring question
    Then the robot should acknowledge that it is thinking while the answer is prepared
    And the robot should speak the answer once it is ready

  # Why: A dropped local WS must recover locally — never trigger a cloud reconnect (D3 closure)
  @edge-case
  Scenario: The robot recovers a dropped local voice connection without falling back to the cloud
    Given the student is mid-conversation with the robot on the local voice server
    When the connection to the local voice server drops
    Then the robot should recover its open-mic conversation on the local voice server
    And no speech-to-speech session should be established with the hosted cloud service
