# Generated by /feature-spec
# Feature: DeepAgents Tutoring Loop with Coach
# Stack: python
# Assumptions: 11 (see deepagents-tutoring-loop_assumptions.yaml)
# Generated: 2026-04-29

@phase-1 @feat-ph1-003 @tutoring-loop @coach
Feature: DeepAgents Tutoring Loop with Coach
  As the Study Tutor system
  I want every Player response gated by an evaluation-only Coach
    against a weighted pedagogical rubric, with revisions on failure,
    a session-end narrative summary, and fire-and-forget persistence
    of misconceptions and the session episode
  So that learners only see curriculum-accurate, AO-aligned, scaffolded responses,
    so that the student model gets richer at no caller-latency cost,
    and so that no caller-facing path ever waits on the knowledge graph.

  Background:
    Given a tutoring session is active for Lilymay on a planned topic
    And the Player is configured with the fine-tuned tutor and a Player prompt
    And the Coach is configured as an evaluation-only agent with no tools
    And the Coach uses a different provider than the Player
    # [ASSUMPTION: confidence=high] Six rubric criteria: curriculum accuracy, AO alignment, scaffolding depth, grade-appropriate language, constructive feedback, quote fidelity
    And the Coach rubric has six weighted criteria with an acceptance threshold
    # [ASSUMPTION: confidence=high] Maximum revisions per turn: 3 (phase-1-scope §FEAT-PH1-003.1)
    And the maximum number of Player revision attempts per turn is bounded
    And the Graphiti write helper is the single dispatch surface for every write
    And every Graphiti write site is fire-and-forget from the caller's perspective

  # ==========================================================================
  # GROUP A: Key Examples
  # ==========================================================================

  # Why: Core happy path — Player passes Coach on first attempt and the student sees the response
  @task:TASK-DTL-003
  @key-example @smoke @player-coach
  Scenario: A Player response that meets the Coach threshold is emitted to the learner
    Given the learner has just sent a turn message
    When the Player produces a response
    And the Coach evaluates the response against the rubric
    # [ASSUMPTION: confidence=high] Acceptance threshold: weighted score >= 0.70
    And the weighted Coach score meets or exceeds the acceptance threshold
    Then the Coach decision should be "accept"
    And the Player's response should be returned to the learner
    And the Coach's reasoning should be recorded in session-only logs
    And the Coach's reasoning should never be shown to the learner

  # Why: The revision loop is the entire point of having a Coach — a rejected response must trigger Player to revise
  @task:TASK-DTL-003
  @key-example @smoke @revision-loop
  Scenario: A Player response below the threshold triggers a revision that is then accepted
    Given the learner has just sent a turn message
    And the Player's first response scores below the acceptance threshold
    # [ASSUMPTION: confidence=medium] Coach feedback to Player on revision is structured rubric scores plus structured "what to improve" — not pasted Coach free-text prose
    When the Player is asked to revise using the Coach's rubric feedback
    And the revised response scores at or above the acceptance threshold
    Then the Coach decision on the revision should be "accept"
    And the revised response should be returned to the learner
    And the original below-threshold response should never be shown to the learner

  # Why: All six rubric criteria are weighted — the score is a weighted sum, not a min or majority
  @task:TASK-DTL-002
  @key-example @rubric
  Scenario: The Coach reports a per-criterion score and a weighted total
    Given the learner has just sent a turn message
    When the Coach evaluates the Player's response
    Then the Coach output should include a score for curriculum accuracy
    And a score for AO alignment
    And a score for scaffolding depth
    And a score for grade-appropriate language
    And a score for constructive feedback
    And a score for quote fidelity
    And a single weighted total derived from the criteria and their weights
    And a list of any misconceptions the Coach observed in the learner's turn

  # Why: Misconceptions are how the student model gets richer over time — Coach owns this write per DDR-002
  @task:TASK-DTL-004
  @key-example @smoke @async @misconception
  Scenario: A misconception observed by the Coach is persisted without blocking the turn return
    Given the Coach is evaluating a Player response
    When the Coach identifies a misconception in the learner's turn
    # [ASSUMPTION: confidence=high] Per-turn budget: p95 < 30 seconds
    Then the turn should return to the caller within the per-turn latency budget
    And a misconception-observed episode should eventually be persisted for the learner
    And the Coach should be the dispatcher of that persistence write
    And a write failure should be logged but never raised to the caller

  # Why: Session-end summary is the second-half outcome of the loop — it consolidates the session for next time
  @task:TASK-DTL-005
  @key-example @smoke @session-end @summary
  Scenario: Ending a session produces a session-completed episode with topics, AOs, turns, and narrative
    Given the session has had several tutor turns and at least one observed misconception
    When the learner ends the session
    # [ASSUMPTION: confidence=high] Session-end caller-facing budget: < 2 seconds
    Then the caller-facing acknowledgement should return within the session-end budget
    And a session-completed episode should eventually be persisted for the learner
    And the persisted episode should record the topics covered
    And the persisted episode should record the assessment objectives exercised
    And the persisted episode should record the number of turns and the duration
    # [ASSUMPTION: confidence=medium] Narrative summary is one to two sentences (both lengths acceptable)
    And the persisted episode should include a short narrative summary of the session
    And the persisted episode should include the misconceptions surfaced during the session

  # Why: Events bus is the source of truth for subscribers; per DDR-003 it must not wait on the Graphiti write
  @task:TASK-DTL-005
  @key-example @events @async
  Scenario: The session.completed event emits on state transition, before the Graphiti write is scheduled
    Given the session has had at least one tutor turn
    When the learner ends the session
    Then the session.completed event should fire on the active-to-ended state transition
    And the session.completed event should fire before the session-end Graphiti write task is scheduled
    And subscribers should observe the event regardless of whether the Graphiti write succeeds

  # Why: Quote verification is the criterion that integrates with the source-typed RAG layer
  @task:TASK-DTL-002
  @key-example @rubric @quote-fidelity
  Scenario: A primary-text quote in the Player response is annotated and scored as fidelity-passing
    Given the session is on a primary text whose canonical edition is in the corpus
    And the Player's response contains a verbatim quote from that primary text
    When the quote verifier is run on the response before the Coach evaluates it
    Then the quote should be annotated with its canonical citation
    And the Coach's quote-fidelity score for the response should pass
    And the annotated response should be the version evaluated by the Coach

  # Why: Coach is structurally not a tutor — D5 invariant from agentic-dataset-factory carries forward
  @task:TASK-DTL-001
  @key-example @invariant @coach-shape
  Scenario: The Coach is constructed without tools and never produces learner-visible output
    Given the Coach factory is asked to construct a Coach for the session
    When the Coach is constructed
    Then the Coach should be configured with no tools
    And the Coach should have no filesystem access surface
    And no Coach-produced text should be returned to the learner under any branch of the loop

  # ==========================================================================
  # GROUP B: Boundary Conditions
  # ==========================================================================

  # Why: Threshold is the single load-bearing number in the loop — the just-inside / just-outside pair must be explicit
  @task:TASK-DTL-002
  @boundary @rubric
  Scenario Outline: Scores at and around the acceptance threshold drive the accept-or-revise decision
    Given the learner has just sent a turn message
    When the Player produces a response that scores <score>
    Then the Coach decision should be <decision>

    Examples:
      | score | decision |
      | 0.70  | accept   |
      | 0.69  | revise   |
      | 1.00  | accept   |
      | 0.00  | revise   |

  # Why: Revision budget is bounded — at exhaustion the loop must release the lowest-scoring reply, not loop forever
  @task:TASK-DTL-003
  @boundary @revision-loop
  Scenario: Three consecutive sub-threshold revisions release the lowest-scoring reply with a silent marker
    Given the learner has just sent a turn message
    And every Player response and revision so far has scored below the acceptance threshold
    When the maximum number of revision attempts has been reached
    Then the lowest-scoring reply observed across the attempts should be returned to the learner
    And a silent log marker should be recorded for session-end review
    And no further revision should be attempted on this turn

  # Why: Coach reasoning length is bounded by prompt instruction so reasoning logs stay tractable
  @task:TASK-DTL-001
  @boundary @coach-shape
  Scenario Outline: Coach reasoning at and around the length cap is recorded as expected
    # [ASSUMPTION: confidence=high] Reasoning length cap: 200 words
    # [ASSUMPTION: confidence=low] Behaviour beyond the cap: recorded in full but flagged as long for session-end review (no truncation, no rejection)
    When the Coach produces reasoning of approximately <length> words
    Then the recorded reasoning length should be <outcome>

    Examples:
      | length | outcome                              |
      | 199    | recorded in full                     |
      | 200    | recorded in full                     |
      | 201    | recorded in full but flagged as long |

  # Why: Per-turn latency budget is the hard constraint that justifies async writes and the revise-or-fallback rule
  @task:TASK-DTL-003
  @boundary @latency
  Scenario Outline: Turn latency at and around the per-turn budget meets or breaches the budget
    When a turn completes its Player-Coach loop in <elapsed> seconds
    Then the turn outcome should be <outcome>

    Examples:
      | elapsed | outcome                                            |
      | 29.99   | within the per-turn budget                         |
      | 30.00   | within the per-turn budget                         |
      | 30.01   | over the per-turn budget; logged for review        |

  # Why: tutor_session_end has its own tighter budget that must hold even when Graphiti is slow
  @task:TASK-DTL-005
  @boundary @latency @async
  Scenario: Session-end returns within budget even when the Graphiti write helper would take much longer
    Given the Graphiti write helper is configured to take longer than the session-end budget
    When the learner ends the session
    Then the caller-facing acknowledgement should still return within the session-end budget
    And the session-end Graphiti write should still be dispatched as a background task

  # Why: The narrative summary length is part of the session-end contract; just-inside vs just-outside must be made explicit
  @task:TASK-DTL-005
  @boundary @summary
  Scenario Outline: The session-end narrative summary stays within the prescribed sentence range
    # [ASSUMPTION: confidence=medium] Acceptable narrative summary lengths: one or two sentences
    When a session-end summary is generated
    Then the narrative summary should consist of <sentences> sentences

    Examples:
      | sentences |
      | one       |
      | two       |

  # Why: Min-quote-length boundary is the verifier's contract; quote_fidelity scoring depends on it
  @task:TASK-DTL-002
  @boundary @quote-fidelity
  Scenario Outline: The quote verifier only inspects quoted spans at or above the minimum length
    # [ASSUMPTION: confidence=high] Minimum quoted-span length for verification: 4 words (FEAT-PH1-004 §4)
    Given the Player response contains a quoted span of <words> words
    Then the verifier should <action>

    Examples:
      | words | action                              |
      | 3     | ignore the span                     |
      | 4     | inspect and verify the span         |
      | 5     | inspect and verify the span         |

  # Why: Empty rubric prompt is the just-outside constructor boundary — must fail loudly before any session uses it
  @task:TASK-DTL-001
  @boundary @negative @coach-shape
  Scenario: Constructing the Coach with an empty system prompt fails before the agent is built
    When the Coach factory is invoked with an empty system prompt
    Then construction should fail with an error indicating the prompt is required
    And no agent should be returned

  # ==========================================================================
  # GROUP C: Negative Cases
  # ==========================================================================

  # Why: Coach output must be schema-checked — malformed Coach output cannot be allowed to corrupt the loop
  @task:TASK-DTL-002
  @negative @rubric
  Scenario: A Coach response that does not match the expected schema is treated as a transient failure
    Given the Coach returns text that cannot be parsed as the expected verdict shape
    # [ASSUMPTION: confidence=medium] Malformed Coach output policy mirrors Coach-unreachable: apply the documented unevaluated-turn fallback; do not persist any misconception derived from the malformed output; flag the turn for session-end review
    When the loop processes the Coach output
    Then the loop should treat the turn under the Coach-fallback policy
    And no malformed Coach output should be persisted as a misconception
    And the failure should be logged for session-end review

  # Why: Coach unreachable is a documented fallback path — the loop must not lock up when the Coach provider fails
  @task:TASK-DTL-003
  @negative @fallback
  Scenario: The Coach provider is unreachable for an entire turn
    Given the Coach provider returns no response within its evaluation budget
    When the loop processes the unevaluated turn
    Then the Player's response should still be returned to the learner under the documented fallback policy
    And the turn should be flagged for session-end review
    And no revision attempts should be made against an absent Coach evaluation

  # Why: Mid-session writes must never raise into the handler — this is the load-bearing async-write guarantee
  @task:TASK-DTL-004
  @negative @async @misconception
  Scenario: A misconception write that fails inside Graphiti does not surface to the caller
    Given a misconception has been observed by the Coach
    When the Graphiti write helper raises an error during the misconception write
    Then the error should be logged with structured fields
    And the error should not be raised from the turn handler
    And the turn should still return successfully to the learner

  # Why: Session-end write failure is symmetric to the mid-session case but applies at the session-end budget
  @task:TASK-DTL-005
  @negative @async @session-end
  Scenario: A session-end Graphiti write failure does not stop the session ending cleanly
    Given the learner has ended the session
    When the session-end Graphiti write task fails after dispatch
    Then the failure should be logged with structured fields
    And the session-completed event should still have been emitted on state transition
    And the caller should still observe the session as ended

  # Why: Role separation is structural, not prompt-based — Coach cannot be allowed to call tools even by mistake
  @task:TASK-DTL-001
  @negative @invariant @coach-shape
  Scenario: A Coach configuration that includes any tools is rejected at construction
    When the Coach factory is invoked with a non-empty tools list
    Then construction should fail with an error indicating tools are forbidden for the Coach
    And no agent should be returned

  # Why: Coach must never become a second tutor — output leaking to the learner is a hard failure
  @task:TASK-DTL-003
  @negative @invariant
  Scenario: A misconfigured loop that would expose Coach reasoning to the learner is detected and refused
    Given a loop configuration would route Coach reasoning into the learner-facing response
    When the configuration is validated at session start
    Then session start should fail with an error indicating Coach output may not reach the learner

  # Why: Two-provider rule is an explicit invariant from agentic-dataset-factory — same provider for both is forbidden
  @task:TASK-DTL-001
  @negative @invariant @coach-shape
  Scenario: A Coach configured to use the same provider as the Player is refused at construction
    Given the Player is configured with a provider
    # [ASSUMPTION: confidence=medium] The two-provider invariant is enforced at Coach factory construction time (factory raises an error if both are configured to the same provider)
    When the Coach factory is invoked with the same provider
    Then construction should fail with an error indicating Coach and Player must differ
    And no agent should be returned

  # ==========================================================================
  # GROUP D: Edge Cases
  # ==========================================================================

  # Why: Two flush points can be in flight simultaneously — they must not interfere or share state
  @task:TASK-DTL-004
  @edge-case @async @concurrency
  Scenario: A misconception write in flight at session end coexists with the session-end write
    Given the Coach has dispatched a misconception write that has not yet completed
    When the learner ends the session
    Then the session-end write should be dispatched as a separate background task
    And both writes should run to completion or failure independently
    And neither write should block or be blocked by the other

  # Why: Multiple misconceptions in one turn must each get their own write, per DDR-002 per-observation ownership
  @task:TASK-DTL-004
  @edge-case @async @misconception
  Scenario: Two misconceptions observed in the same turn are written as two independent episodes
    Given the Coach observes two distinct misconceptions in a single turn
    When the misconception writes are dispatched
    Then each misconception should be persisted as its own episode
    And neither misconception write should be batched with the other
    And a failure of one write should not affect the other

  # Why: Session abandoned before any tutor turn must NOT emit session.completed — preserves I-T6 invariant
  @task:TASK-DTL-005
  @edge-case @events @invariant
  Scenario: Ending a session that never produced a tutor turn does not emit session.completed
    Given a session has been started but no tutor turn has been produced
    When the learner ends the session
    Then the session-completed event should not be emitted
    And no session-completed Graphiti episode should be scheduled

  # Why: AO3 contextual content path bypasses primary-text retrieval; quote_fidelity must not penalise the Player for that
  @task:TASK-DTL-002
  @edge-case @quote-fidelity @retrieval
  Scenario: A turn that runs in analysis mode is not penalised on quote fidelity for the absence of retrieved evidence
    Given the session-plan focus is contextual and retrieval is skipped
    When the Player produces a response that contains no primary-text quotes
    Then the Coach should not down-rank the response on quote fidelity
    And the turn metadata should record that retrieval was skipped with a reason

  # Why: A fabricated quote must be removed before it reaches the learner, not merely down-ranked
  @task:TASK-DTL-002
  @edge-case @quote-fidelity @safety
  Scenario: A fabricated primary-text quote in the Player response is corrected before the Coach evaluates
    Given the Player produces a response containing a quoted phrase that does not appear in the corpus
    When the quote verifier processes the response before the Coach evaluates it
    Then the unmatched quote should be removed or rewritten as paraphrase
    And the Coach should evaluate the rewritten response, not the original
    And the rewrite should be observable in the turn's recorded metadata

  # Why: Filesystem-backed corpus contents could carry malicious filename-style content; Coach must not be tricked into a tool call
  @task:TASK-DTL-001
  @edge-case @security @coach-shape
  Scenario: Adversarial content in the corpus does not cause the Coach to attempt a tool call
    Given the corpus contains a chunk whose text resembles a tool-call instruction
    When the Coach evaluates a Player response that quotes the adversarial chunk
    Then the Coach should produce its verdict as text only
    And no tool-call should be attempted by the Coach

  # Why: Misconception text comes from learner input — sanitisation is critical before it reaches the write helper
  @task:TASK-DTL-004
  @edge-case @security @async
  Scenario: A misconception derived from learner-supplied text is sanitised before the write is dispatched
    Given the learner's turn contains text resembling a prompt-injection attempt
    When the Coach records a misconception derived from that turn
    Then the misconception payload should be sanitised before dispatch
    And the persisted episode should not contain unescaped injection markers

  # Why: A graceful shutdown must not silently drop in-flight writes — DDR-002 promises a drain on shutdown
  @task:TASK-DTL-004
  @edge-case @async @lifecycle
  Scenario: A graceful shutdown drains in-flight Graphiti writes within the shutdown grace window
    Given several Graphiti writes are in flight
    # [ASSUMPTION: confidence=low] Shutdown grace window for in-flight writes: 5 seconds
    When the runtime is asked to shut down gracefully
    Then in-flight writes should be allowed to finish within the shutdown grace window
    And any writes that did not finish within the window should be logged with structured fields

  # Why: Two concurrent sessions must keep their Coach evaluations strictly separated
  @task:TASK-DTL-003
  @edge-case @concurrency
  Scenario: Coach evaluations from two concurrent sessions do not contaminate each other
    Given two sessions are active for two different learners
    When each session has a Player response under Coach evaluation at the same time
    Then each session's accept-or-revise decision should reflect only its own response
    And neither session's misconception write should be attributed to the other learner

  # Why: A revision loop where the Coach changes its mind across attempts must still terminate predictably
  @task:TASK-DTL-003
  @edge-case @revision-loop
  Scenario: A revision attempt that scores below an earlier accepted attempt is not emitted in place of it
    Given a turn that has already been accepted at one revision level
    When a subsequent revision is somehow scored
    Then the originally accepted response should remain the response shown to the learner
    And no further attempt should be made on this turn

  # ==========================================================================
  # GROUP E: Edge Case Expansion — Security, Integration, Concurrency
  # ==========================================================================

  # Why: Coach reasoning is a free-text channel; if treated as Player instructions on revision, a malformed
  #      Coach response could effectively become a covert prompt rewrite
  @task:TASK-DTL-003
  @edge-case @security @revision-loop
  Scenario: Directive-shaped Coach text on a rejected turn is not obeyed by the Player on revision
    Given the Coach rejects a Player response with reasoning that contains directive-shaped text
    # [ASSUMPTION: confidence=medium] Player revision input is structured rubric feedback only — Coach free-text reasoning is not pasted into the Player's system prompt or user message
    When the Player is asked to revise based on that Coach feedback
    Then the Player's revision should be driven by the structured rubric feedback, not by free-text directives
    And no part of the Coach's free-text reasoning should be passed to the Player as a system-level instruction

  # Why: Learner-supplied input could contain an instruction-shaped payload aimed at the Coach's evaluator role
  @task:TASK-DTL-001
  @edge-case @security @coach-shape
  Scenario: A learner turn that contains a prompt-injection attempt against the Coach is evaluated as content
    Given the learner's turn contains text that resembles instructions addressed to the Coach
    When the Coach evaluates the Player's response to that turn
    Then the Coach should produce its verdict as a structured evaluation only
    And the Coach should not change its decision shape, score schema, or output channel based on the learner's text

  # Why: Provider availability can change mid-turn — the loop must not deadlock or silently drop the turn
  @task:TASK-DTL-003
  @edge-case @integration @fallback
  Scenario: The Player provider becomes unavailable between the first response and a requested revision
    Given the Player produced a first response that scored below the acceptance threshold
    When the Player provider is unavailable for the revision attempt
    Then the loop should fall back to the documented unevaluated-turn policy for this turn
    And the turn should be flagged for session-end review with a provider-unavailable reason

  # Why: A failure inside the quote verifier must not propagate as a turn failure — the loop has to keep moving
  @task:TASK-DTL-002
  @edge-case @integration @quote-fidelity
  Scenario: The quote verifier raises an exception while processing a Player response
    Given the quote verifier raises an unexpected exception on a Player response
    When the loop processes the verifier failure
    Then the response should be passed to the Coach unannotated
    And the Coach should evaluate the unannotated response under the documented fallback policy
    And the verifier failure should be logged for session-end review

  # Why: Sessions are append-only and end-once; a slow turn could overlap with a session-end call
  @task:TASK-DTL-005
  @edge-case @concurrency @lifecycle
  Scenario: tutor_session_end is invoked while a tutor_turn for the same session is still in flight
    Given a tutor_turn is still inside its Player-Coach loop for an active session
    When tutor_session_end is invoked for the same session
    Then the in-flight turn should either complete and append before the session is marked ended, or be discarded with no append
    And no tutor turn should be appended to the session after the session has been marked ended
    And no session-completed event should be emitted before the in-flight turn has been resolved one way or the other

  # Why: The shared write helper is the single dispatch surface; it must remain correct under simultaneous calls
  @task:TASK-DTL-004
  @edge-case @concurrency @async
  Scenario: The shared write helper handles simultaneous dispatches from the Coach and the Tutor handler
    Given the Coach is about to dispatch a misconception write
    And the Tutor handler is about to dispatch a topic-confidence-update write
    When both dispatches occur simultaneously
    Then both writes should be scheduled as independent fire-and-forget tasks
    And neither dispatch should block or be blocked by the other
    And the structured-log line for one write should not be conflated with the other
