# Generated by /feature-spec
# Feature: study-tutor NATS Fleet Integration
# Stack: python
# Assumptions: 7 (see nats-fleet-integration_assumptions.yaml)
# Generated: 2026-05-08
# Source: docs/reviews/REVIEW-NATS-FLEET-PATTERNS-2026-05-08.md (canonical)
# Supersedes: features/nats-fleet-integration/nats-fleet-scope-and-build-plan.md (cross-reference only)

@phase-1 @phase-2 @phase-3 @nats-fleet @feat-nats-001
Feature: study-tutor NATS Fleet Integration
  As the study-tutor agent
  I want to participate in the NATS fleet alongside specialist-agent and forge
  So that jarvis (and any future fleet caller) can dispatch tutoring commands
  through the same canonical request/reply contract used by every other agent

  Background:
    Given the NATS server is reachable with valid APPMILLA credentials
    And the agent-registry KV bucket exists
    And the AGENTS and FLEET JetStream streams are provisioned
    And the study-tutor adapter is configured with agent_id "gcse-tutor"
    And the tutor business logic is wired through MCPAdapter

  # ==========================================================================
  # GROUP A: Key Examples — core fleet membership and command round-trips
  # ==========================================================================

  # Why: Boot lifecycle is the foundation — without successful registration the agent is invisible to the fleet
  @task:TASK-NATS-PH1-005
  @key-example @smoke @phase-1 @lifecycle
  Scenario: Adapter boot registers the tutor in the fleet and advertises its capabilities
    Given the adapter has not yet started
    When the adapter starts
    Then the adapter should connect to NATS successfully
    And the tutor manifest should appear in the agent-registry under key "gcse-tutor"
    And the manifest should advertise four tool capabilities
    And the adapter should report itself as ready

  # Why: Heartbeat is the agent's public liveness signal — observers depend on it
  # [ASSUMPTION: confidence=high] Heartbeat interval is 30 seconds (nats-core AgentConfig default)
  @task:TASK-NATS-PH1-005
  @key-example @smoke @phase-1 @lifecycle
  Scenario: A live adapter publishes heartbeats on its fleet subject
    Given the adapter is running and ready
    When 30 seconds have elapsed since the last heartbeat
    Then a heartbeat envelope should be published on the fleet heartbeat subject for this agent

  # Why: The four MCP tools must each round-trip through NATS — single Outline covers the canonical happy path
  # [ASSUMPTION: confidence=high] Per-command maximum execution time is 600 seconds (nats-core max_task_timeout_seconds)
  @task:TASK-NATS-PH1-008
  @key-example @smoke @phase-1 @round-trip
  Scenario Outline: A canonical command round-trips through the NATS adapter to the tutor business logic
    Given the adapter is running and ready
    When jarvis dispatches a "<command>" command for this tutor
    Then the corresponding tutor business logic should be invoked
    And a successful result should be returned to the caller
    And the result should reach the caller within 600 seconds

    Examples:
      | command          |
      | start_session    |
      | tutor_turn       |
      | session_status   |
      | end_session      |

  # Why: Live discovery removes the stub-yaml dependency entirely (Decision 1, 2026-05-08)
  @task:TASK-NATS-PH1-009
  @key-example @smoke @phase-1 @discovery
  Scenario: jarvis discovers the tutor through live capability registration without any stub configuration
    Given jarvis is configured to read capabilities from the live registry
    And no stub-capabilities entry exists for the tutor
    When the tutor adapter completes its boot
    Then jarvis should see "gcse-tutor" as a dispatchable agent
    And jarvis should be able to dispatch a tutor command without any manual configuration step

  # Why: Graceful shutdown is half of the lifecycle contract — without it stale registry entries accumulate
  # [ASSUMPTION: confidence=high] Drain window is 30 seconds (specialist-agent _shutdown_timeout)
  @task:TASK-NATS-PH1-005
  @key-example @phase-1 @lifecycle
  Scenario: Graceful shutdown deregisters the tutor and stops heartbeats
    Given the adapter is running and ready
    When the adapter receives a shutdown signal
    Then any in-flight command should be allowed to complete within 30 seconds
    And the heartbeat loop should stop
    And the tutor's registry entry should be removed
    And the adapter should close its NATS connection cleanly

  # ==========================================================================
  # GROUP B: Boundary Conditions
  # ==========================================================================

  # Why: Just-inside boundary on intents — minimum valid manifest (Bug #5 regression guard)
  @task:TASK-NATS-PH1-002
  @boundary @phase-1 @bug-5
  Scenario: A manifest with exactly one intent capability registers successfully
    Given a manifest with one intent capability and four tool capabilities
    When the adapter registers the manifest
    Then registration should succeed

  # Why: Just-outside boundary on intents — empty intents array must be rejected (Bug #5 regression guard)
  @task:TASK-NATS-PH1-002
  @boundary @negative @phase-1 @bug-5 @regression
  Scenario: A manifest with zero intent capabilities is rejected at registration
    Given a manifest with zero intent capabilities
    When the adapter attempts to register the manifest
    Then registration should fail with a clear validation error
    And the adapter should not enter the ready state

  # Why: Just-inside boundary on agent_id format — kebab-case is the canonical contract from nats-core
  @task:TASK-NATS-PH1-002
  @boundary @phase-1
  Scenario Outline: A kebab-case agent_id is accepted
    Given the adapter is configured with agent_id "<id>"
    When the adapter starts
    Then registration should succeed

    Examples:
      | id          |
      | gcse-tutor  |
      | a           |
      | tutor-1     |

  # Why: Just-outside boundary on agent_id format — non-kebab-case must be rejected
  @task:TASK-NATS-PH1-002
  @boundary @negative @phase-1
  Scenario Outline: A non-kebab-case agent_id is rejected at boot
    Given the adapter is configured with agent_id "<id>"
    When the adapter starts
    Then the adapter should fail to start with a clear configuration error

    Examples:
      | id          |
      | GCSE-Tutor  |
      | gcse_tutor  |
      | 1-tutor     |
      |             |

  # Why: Readiness gating — commands arriving before _ready must be rejected, not lost (Phase 2 hardening)
  @task:TASK-NATS-PH2-001
  @boundary @phase-2 @readiness
  Scenario: A command arriving exactly at the moment the adapter becomes ready is processed
    Given the adapter has connected and registered but is in the process of marking itself ready
    When the readiness state transitions to ready
    And a command arrives immediately after
    Then the command should be processed normally

  # Why: Just-outside the readiness boundary — the same command before ready must be rejected
  @task:TASK-NATS-PH2-001
  @boundary @negative @phase-2 @readiness
  Scenario: A command arriving before the adapter is ready is rejected with a clear error
    Given the adapter has connected but has not yet completed registration
    When a command arrives
    Then the result should indicate the tutor is not ready
    And the result should be returned to the caller
    And the underlying tutor business logic should not be invoked

  # ==========================================================================
  # GROUP C: Negative Cases
  # ==========================================================================

  # Why: An unknown command name must produce an actionable error, not a silent drop
  @task:TASK-NATS-PH1-004
  @negative @phase-1
  Scenario: A command with an unknown name is rejected with a list of supported commands
    Given the adapter is running and ready
    When a command with an unrecognised name is dispatched to the tutor
    Then the result should indicate the command is not supported
    And the error should list the supported commands

  # Why: Malformed envelopes must not crash the adapter
  @task:TASK-NATS-PH1-004
  @negative @phase-1
  Scenario: A malformed command envelope is rejected without disrupting the adapter
    Given the adapter is running and ready
    When a malformed envelope is published on the tutor's command subject
    Then the result should indicate a validation error
    And the adapter should remain ready to accept further commands

  # Why: Bug #3 regression guard — missing /v1 suffix on the LLM base URL must surface clearly
  @task:TASK-NATS-PH3-002
  @negative @phase-3 @bug-3 @regression
  Scenario: A misconfigured LLM base URL surfaces a clear configuration error during a tutor turn
    Given the adapter is running with an LLM base URL missing the version suffix
    When a tutor_turn command is dispatched
    Then the result should indicate a downstream LLM configuration error
    And the error should mention the LLM base URL or upstream endpoint

  # Why: Commands intended for a different agent should never be processed by this adapter
  @task:TASK-NATS-PH1-004
  @negative @phase-1
  Scenario: A command targeted at another agent is not processed by the tutor
    Given the adapter is running and ready
    When a command is published on a different agent's command subject
    Then the tutor business logic should not be invoked
    And the tutor should publish no result for that command

  # Why: NATS unreachable at boot must fail fast — silent retry loops mask deployment problems
  # [ASSUMPTION: confidence=medium] Boot fail-fast bound is 10 seconds — not explicitly capped in source
  @task:TASK-NATS-PH1-005
  @negative @phase-1
  Scenario: An unreachable NATS server at boot fails fast with a clear error
    Given NATS is unreachable
    When the adapter attempts to start
    Then the adapter should fail to start within 10 seconds
    And the error should identify the NATS connectivity problem

  # ==========================================================================
  # GROUP D: Edge Cases — regression guards and operational realities
  # ==========================================================================

  # Why: Bug #1 regression guard — the canonical PubAck race must never resurface
  @task:TASK-NATS-PH1-005
  @edge-case @phase-1 @bug-1 @regression
  Scenario: A reply to a request-style dispatch lands on the caller's inbox, not only on the result topic
    Given the adapter is running and ready
    And a command subject is JetStream-stored under the AGENTS stream
    When the caller dispatches a command using a request/reply pattern with an inbox
    Then the caller should receive the tutor's result envelope on the inbox
    And the caller should not receive a JetStream PubAck as the apparent reply
    And the same result envelope should also be observable on the tutor's result topic

  # Why: Bug #2 regression guard — tool names must resolve to canonical commands via tool_to_command
  @task:TASK-NATS-PH1-004
  @edge-case @phase-1 @bug-2 @regression
  Scenario Outline: A tool-name dispatch resolves to the canonical command through the tool_to_command map
    Given the adapter is running and ready
    When jarvis dispatches with the tool name "<tool>"
    Then the canonical command "<command>" should be invoked
    And a successful result should be returned

    Examples:
      | tool                  | command         |
      | tutor_start_session   | start_session   |
      | tutor_turn            | tutor_turn      |
      | tutor_session_status  | session_status  |
      | tutor_session_end     | end_session     |

  # Why: Bug #4 documentation guard — wire-taps must use the flat agents.command.> pattern
  @task:TASK-NATS-PH3-004
  @edge-case @phase-3 @bug-4 @regression @runbook
  Scenario: A wire-tap on the documented command subject pattern captures a real dispatch
    Given the adapter is running and ready
    And a wire-tap is subscribed to the documented command-fanout subject pattern
    When jarvis dispatches a command to the tutor
    Then the wire-tap should observe the command envelope

  # Why: SIGTERM mid-turn must not orphan an in-flight tutor session
  # [ASSUMPTION: confidence=high] Drain window is 30 seconds (specialist-agent _shutdown_timeout)
  @task:TASK-NATS-PH1-006
  @edge-case @phase-1 @lifecycle
  Scenario: SIGTERM during an in-flight tutor turn drains the request before deregistration
    Given the adapter is running and ready
    And a tutor_turn command is currently being processed
    When the adapter receives SIGTERM
    Then the in-flight tutor turn should be allowed to complete within 30 seconds
    And the result for that turn should reach the caller before the adapter exits
    And the registry entry should then be removed

  # Why: NATS reconnect mid-session should preserve the in-memory session for the demo path
  # [ASSUMPTION: confidence=medium] Reconnect window is 60 seconds — aligns with heartbeat_timeout=90s
  @task:TASK-NATS-PH1-005
  @edge-case @phase-1 @resilience
  Scenario: The adapter reconnects to NATS after a transient disconnect without losing live sessions
    Given the adapter is running with one active tutor session
    When the NATS connection drops and recovers within 60 seconds
    Then the adapter should re-establish its subscription
    And the active session should still be addressable by its session_id
    And subsequent tutor_turn commands for that session should succeed

  # Why: Container restart is an acknowledged limitation pre-FU-001 (hybrid Graphiti durability)
  @task:TASK-NATS-PH3-004
  @edge-case @phase-3 @known-limitation
  Scenario: Active sessions are lost when the tutor container restarts
    Given the adapter is running with one active tutor session
    When the container restarts
    Then the adapter should boot cleanly with a fresh session store
    And a tutor_turn command for the prior session_id should be rejected as an unknown session
    And the runbook should document this as a known pre-FU-001 limitation

  # Why: Stale registry entries are an operational reality until the jarvis-side reaper lands (Decision 3)
  @task:TASK-NATS-PH2-003
  @edge-case @phase-2 @runbook @known-limitation
  Scenario: A killed tutor leaves a stale registry entry that operators clean up manually
    Given the adapter was running with a registered manifest
    When the tutor process is killed without a graceful shutdown
    Then the registry entry for "gcse-tutor" should still be present
    And the runbook should document the manual cleanup command for stale entries

  # ==========================================================================
  # GROUP E: Security
  # ==========================================================================

  # Why: Bad credentials must fail at the door — not surface later as confusing dispatch errors
  # [ASSUMPTION: confidence=medium] Boot fail-fast bound is 10 seconds for credential rejection
  @task:TASK-NATS-PH1-005
  @edge-case @security @phase-1
  Scenario: An adapter started with invalid NATS credentials fails closed at boot
    Given the adapter is configured with credentials that NATS will reject
    When the adapter attempts to start
    Then the adapter should fail to start within 10 seconds
    And the error should identify the authentication failure
    And no manifest should be registered

  # Why: agent_id collisions corrupt routing — the second claimant must lose, not silently overwrite
  @task:TASK-NATS-PH2-001
  @edge-case @security @phase-2 @split-brain
  Scenario: A second adapter claiming the same agent_id is rejected after the first is registered
    Given an adapter is already running and registered as "gcse-tutor"
    When a second adapter attempts to start with the same agent_id
    Then the second adapter should refuse to register or refuse to start
    And the existing tutor's registry entry should remain unchanged
    And the existing tutor should continue receiving commands

  # ==========================================================================
  # GROUP F: Concurrency
  # ==========================================================================

  # Why: Per-session ordering is a contract — concurrent turns must not interleave Coach feedback
  @task:TASK-NATS-PH1-004
  @edge-case @concurrency @phase-1
  Scenario: Two concurrent tutor_turn commands for the same session are serialised
    Given the adapter is running and ready
    And one active tutor session exists
    When two tutor_turn commands for that session are dispatched simultaneously
    Then both commands should be processed without interleaving the per-turn business logic
    And both results should be returned to their respective callers
    And the session transcript should preserve a consistent turn order

  # Why: Shutdown races are common in container orchestration — the fix is "drain, then deregister"
  @task:TASK-NATS-PH1-005
  @edge-case @concurrency @phase-1 @lifecycle
  Scenario: A command arriving during the deregister phase of shutdown is handled cleanly
    Given the adapter is running and has begun graceful shutdown
    When a command arrives after deregister has started but before NATS close
    Then the command should either complete normally or return a clear "shutting down" error
    And the adapter should not crash
    And the registry entry should still be removed

  # ==========================================================================
  # GROUP G: Data integrity
  # ==========================================================================

  # NOTE: A duplicate-delivery idempotency scenario was proposed but DEFERRED on 2026-05-08.
  # Decision: jarvis MUST NOT duplicate-dispatch (contract pushed upstream). Tutor behaviour
  # under duplicate delivery is undefined for the demo. If duplicate delivery is observed in
  # a runbook, revisit via TASK-NATS-FU-005. See ASSUM-007 in _assumptions.yaml.

  # Why: Silent truncation of an oversized result is the worst possible failure mode
  # [ASSUMPTION: confidence=high] NATS max message size is 1 MB (nats-infrastructure config max_payload=1048576)
  @task:TASK-NATS-PH3-005
  @edge-case @data-integrity @phase-3
  Scenario: A result envelope exceeding the NATS max message size produces a clear error
    Given the adapter is running and ready
    And a tutor command would produce a result larger than 1 MB
    When the command is dispatched
    Then the result should not be silently truncated
    And the caller should receive a clear error indicating the result exceeded the size limit
    And the runbook should document this limit and the recommended mitigation

  # ==========================================================================
  # GROUP H: Integration boundaries
  # ==========================================================================

  # Why: When llama-swap is down the tutor must surface this clearly, not look like a bug in the tutor
  @task:TASK-NATS-PH3-005
  @edge-case @integration @phase-3
  Scenario: LLM unreachable mid-tutor_turn produces a clear upstream error and preserves session integrity
    Given the adapter is running and ready with one active session
    And the LLM endpoint is unreachable
    When a tutor_turn command is dispatched for that session
    Then the result should indicate an upstream LLM connectivity error
    And the session should remain addressable for retry once the LLM recovers
    And the session transcript should not contain a partial or corrupted turn

  # Why: Missing infra at boot must fail loudly — silent skip causes a "ghost agent" symptom
  @task:TASK-NATS-PH3-005
  @edge-case @integration @phase-3
  Scenario: A missing agent-registry KV bucket at boot fails the adapter rather than silently skipping registration
    Given the agent-registry KV bucket does not exist
    When the adapter attempts to start
    Then the adapter should fail to start with a clear error naming the missing bucket
    And the runbook should reference the nats-infrastructure provisioning step
