# Generated by /feature-spec
# Feature: Durable Cross-Device Sessions (FEAT-SMP-003)
# Stack: python
# Assumptions: 12 (see durable-cross-device-sessions_assumptions.yaml)
# Generated: 2026-07-04T11:37:04Z
# Scope: FEAT-SMP-003 — the 6 PostgresStudentStore session methods over the merged
#   W1 session/session_turn schema; wire the (already-built) SessionService into both
#   MCP adapter sites; server-resolve a single-user identity (config, default lilymay)
#   kept SEPARATE from the planner slug; swap the 4 MCP tools onto SessionService with
#   the MCP + NATS surface byte-for-byte unchanged; move session-END onto Postgres
#   (port Phase1MinimalDeltaPolicy over W2 store reads → ConfidenceUpdate[], durable
#   record_session_completion, preserve the live session.completed payload).
# RESOLVED in the scope decision: identity = config single-user; xp_awarded = 0
#   placeholder; misconceptions empty-but-plumbed; session.completed payload preserved;
#   confidence delta = ported Phase1MinimalDeltaPolicy over store reads.
# Out of scope: HTTP/WS transport + turn_stream (mobile /goal); a real XP/gamification
#   engine; wiring the Coach verdict into misconceptions; the full Graphiti teardown incl.
#   deleting session.tutor_session (FEAT-SMP-004 — the adapter just stops using it).
# REVIEW REQUIRED: 3 low-confidence assumptions — resume-if-active atomicity (ASSUM-003),
#   the confidence-delta port semantics (ASSUM-008), the preserved session.completed
#   payload vs events-schema.yaml divergence (ASSUM-010).

@phase-1 @feat-smp-003 @sessions @postgres @cross-device
Feature: Durable Cross-Device Sessions
  As a student using study-tutor from more than one device
  I want my study sessions persisted, resumable, and closed with my learner state recorded
  So that I can pick up where I left off on another device and my progress is durably saved

  Background:
    Given a study-tutor Postgres store with the FEAT-SMP-001 schema applied
    And the learner "lilymay" exists in the store

  # ==========================================================================
  # GROUP A: Key Examples
  # ==========================================================================

  # Why: The headline — a session is now durable and keyed to the student, not in-memory
  @task:TASK-SMP3-01
  @key-example @smoke @lifecycle
  Scenario: Starting a session creates a durable session keyed to the learner
    When lilymay starts a session on the subject "english-literature"
    Then a new active session should be created and returned
    And the session should belong to lilymay
    And it should start with no turns recorded

  # Why: Per-turn durability is what makes a mid-session device switch lossless
  @task:TASK-SMP3-03
  @key-example @smoke @lifecycle
  Scenario: Taking a turn durably records the learner message and the tutor reply
    Given lilymay has an active session
    When she sends the message "What does the dagger symbolise?"
    Then both her message and the tutor's reply should be durably recorded on the session
    And the session's turn count should advance to include them

  # Why: Cross-device resume — a device that did not start the session loads the thread
  @task:TASK-SMP3-02
  @key-example @resume
  Scenario: Resuming an active session returns its full transcript
    Given lilymay has an active session with several recorded turns
    When she resumes that session
    Then the ordered transcript of every recorded turn should be returned
    And the session should still be active

  # Why: The "resume where you left off" list a device shows on open
  @task:TASK-SMP3-02
  @key-example @lifecycle
  Scenario: Listing sessions shows the learner's sessions most recently active first
    Given lilymay has three recorded sessions with different last-activity times
    When her sessions are listed
    Then they should be returned most recently active first

  # Why: Session-end is now one synchronous Postgres write (XP/confidence), not a Graphiti flush
  @task:TASK-SMP3-05
  @key-example @smoke @session-end
  Scenario: Ending a session marks it ended and records the learner-state deltas
    Given lilymay has an active session with recorded turns on "Macbeth Act 1"
    When the session is ended
    Then the session should be marked ended
    And her resolved confidence for the covered topic should be recorded
    And a session-completed notification should be emitted

  # Why: Status is the read a device polls to decide whether it can resume
  @task:TASK-SMP3-01
  @key-example @lifecycle
  Scenario: Requesting session status returns its lifecycle state and turn count
    Given lilymay has an active session with two recorded turns
    When the session's status is requested
    Then it should report the session as active with a turn count of two
    And it should report the session as resumable

  # ==========================================================================
  # GROUP B: Boundary Conditions
  # ==========================================================================

  # Why: resume-if-active is the create-or-resume boundary the start verb hinges on
  @task:TASK-SMP3-01
  @boundary @resume
  Scenario Outline: Starting with resume-if-active creates or resumes depending on existing state
    Given lilymay has <existing> active session on the subject "english-literature"
    When she starts a session on "english-literature" with resume-if-active
    Then the session should be <outcome>

    Examples:
      | existing | outcome                        |
      | no       | newly created                  |
      | an       | resumed with its transcript    |

  # Why: Turn indexing is zero-based and monotonic — the ordering the transcript relies on
  @task:TASK-SMP3-03
  @boundary @lifecycle
  Scenario: The first turn is recorded at index zero and the count advances by one per turn
    Given lilymay has a newly created session with no turns
    When two turns are recorded in order
    Then the first turn should be at index zero and the second at index one
    And the session's turn count should be two

  # Why: The resume list is paged — a device asks for a bounded number
  @task:TASK-SMP3-02
  @boundary @lifecycle
  Scenario: Listing respects the requested limit and returns the most recent
    Given lilymay has five recorded sessions
    When her sessions are listed with a limit of two
    Then at most two sessions should be returned, the two most recently active

  # Why: I-T6 zero-turn rule — closing an empty session must not write learner-state deltas
  @task:TASK-SMP3-06
  @boundary @session-end
  Scenario: Ending a session that has no turns closes it without recording learner-state deltas
    Given lilymay has an active session with no turns
    When the session is ended
    Then the session should be marked ended
    And no learner-state deltas should be recorded
    And no session-completed notification should be emitted

  # Why: §9 carve-out — status is the one verb that may read an ended session
  @task:TASK-SMP3-01
  @boundary @lifecycle
  Scenario: Session status is available even after a session has ended
    Given lilymay has a session that has ended
    When the session's status is requested
    Then it should report the session as ended and not resumable

  # ==========================================================================
  # GROUP C: Negative Cases / Guards
  # ==========================================================================

  # Why: ended is terminal — a mutating verb on it is refused (SessionEnded)
  @task:TASK-SMP3-03
  @negative @guard
  Scenario: Taking a turn on an ended session is refused
    Given lilymay has a session that has ended
    When she tries to send a message on that session
    Then the action should be refused because the session has ended

  # Why: Unknown session id is a typed not-found, not a crash
  @task:TASK-SMP3-03
  @negative @guard
  Scenario: Acting on an unknown session reports the session as not found
    When an action is taken on a session identifier that does not exist
    Then it should report that the session was not found

  # Why: Ownership guard — one student may never touch another's session (SessionForbidden)
  @task:TASK-SMP3-06
  @negative @guard @security
  Scenario: Acting on a session owned by another learner is forbidden
    Given the learner "rowan" also exists with his own active session
    When lilymay tries to act on rowan's session
    Then the action should be forbidden because the session is not hers

  # Why: Resume only works while active — resuming an ended session is refused
  @task:TASK-SMP3-06
  @negative @guard @resume
  Scenario: Resuming an ended session is refused
    Given lilymay has a session that has ended
    When she tries to resume that session
    Then the action should be refused because the session has ended

  # Why: Sessions and their learner-state writes are keyed to a real student (FK)
  @task:TASK-SMP3-05
  @negative @guard
  Scenario: Recording a completed session for an unknown learner is rejected
    Given no learner "ghost" exists in the store
    When a completed session is recorded for "ghost"
    Then the write should be rejected and nothing should be persisted

  # ==========================================================================
  # GROUP D: Edge Cases / Migration Semantics
  # ==========================================================================

  # Why: Durability is the whole point — state must survive a process restart
  @task:TASK-SMP3-07
  @edge-case @durability
  Scenario: A session and its turns survive a process restart
    Given lilymay has an active session with recorded turns
    When the backend is restarted and the session is read again
    Then the session and its full ordered transcript should still be present

  # Why: Cross-device pickup — the same authenticated student resumes the same session elsewhere
  @task:TASK-SMP3-01
  @edge-case @cross-device @resume
  Scenario: A second device authenticated as the same learner resumes the same active session
    Given lilymay started a session on one device and recorded some turns
    When she opens study-tutor on a second device authenticated as the same learner
    Then she should see that active session and be able to resume its transcript

  # [ASSUMPTION: confidence=low] The confidence delta is the ported Phase1MinimalDeltaPolicy over store reads; with misconceptions empty, only the +1 engagement bonus (>=5 turns, no misconceptions) is live.
  # Why: Session-end confidence is now derived from the store, not a Graphiti node
  @task:TASK-SMP3-05
  @edge-case @session-end
  Scenario: Ending a session derives the confidence update from the learner's current stored confidence
    Given lilymay has a recorded confidence on "Macbeth Act 1"
    And she has completed at least five turns on it with no observed misconceptions
    When the session is ended
    Then her recorded confidence on "Macbeth Act 1" should be nudged up by the engagement bonus

  # Why: A retried session-end must not double-write the learner state (idempotent on session id)
  @task:TASK-SMP3-06
  @edge-case @session-end @idempotency
  Scenario: Re-delivering the same completed session records the learner-state deltas only once
    Given lilymay's session has already been recorded as completed
    When the identical session completion is delivered again under the same session identifier
    Then her persisted learner state should be unchanged by the repeat

  # Why: The swap onto the durable store must not alter the tutor tool surface agents depend on
  @task:TASK-SMP3-06
  @edge-case @regression @surface
  Scenario: The tutor tool surface is unchanged after moving sessions onto the durable store
    Given the tutor tools are served over the agent surface
    When the tool surface is inspected
    Then the same four session tools should be present with unchanged names and descriptions
    And ending a session should still report only the session identifier and an ended status
    And the not-found, ended, and forbidden errors should keep their existing shapes

  # Why: Timestamps cross the boundary as timezone-aware UTC (parity with W1/W2)
  @task:TASK-SMP3-01
  @edge-case @durability
  Scenario: Session and turn timestamps are timezone-aware UTC
    Given lilymay has an active session with a recorded turn
    When the session and its turns are read back
    Then their timestamps should be timezone-aware and expressed in UTC
