# Generated by /feature-spec
# Feature: Student Model Postgres Store — Reads
# Stack: python
# Assumptions: 11 (see student-model-postgres-store-reads_assumptions.yaml)
# Generated: 2026-07-03T21:12:27Z
# Scope: FEAT-SMP-002 / W2 only — the read path over the merged W1 schema:
#   get_student_state, get_topic_confidences, get_recent_misconceptions on
#   PostgresStudentStore, behind knowledge.store.reads, preserving the
#   graceful-degradation contract; plus repointing the planner read off the
#   retired Graphiti path and removing the Graphiti read copies from queries.py.
#   Out of scope: the write path (FEAT-SMP-001, merged); session create/append/
#   list/end (FEAT-SMP-003, gated by G-CON); the graph WRITE-path removal and
#   the graph seed-script migration (a later cutover, FEAT-SMP-004).
# RESOLVED during spec review:
#   (ASSUM-003) confidence_band_at_observation is approximated at read time from
#     the current topic_confidence band (default "struggling") — the misconception
#     table does not persist band-at-observation.
#   (ASSUM-007) the store is wired at serve startup only when STUDY_TUTOR_PG_DSN
#     is set; otherwise the runtime stays unwired and reads degrade to empty.
#   (ASSUM-004/005) most_recent_session_id is read from the session table; the
#     Graphiti-era "stale" flag is retired (always False).
# REVIEW REQUIRED: 3 low-confidence assumptions remain — band-at-observation
#   approximation (ASSUM-003), conditional startup wiring (ASSUM-007), and the
#   seed-script/queries read-copy removal coupling (ASSUM-010).

@phase-1 @feat-smp-002 @student-model @postgres @reads
Feature: Student Model Postgres Store — reads
  As the study-tutor backend
  I want the learner snapshot, per-topic confidences, and recent misconceptions read from the study-tutor-owned Postgres store
  So that the planner and handlers see real learner state through the same graceful-degradation contract the retired Graphiti read path guaranteed

  Background:
    Given a study-tutor Postgres store with the FEAT-SMP-001 schema applied

  # ==========================================================================
  # GROUP A: Key Examples
  # ==========================================================================

  # Why: The aggregate snapshot the handlers read — the primary read surface
  @task:TASK-SMP2-03
  @key-example @smoke @read-path
  Scenario: Reading the snapshot for a known learner returns her profile, confidences, and recent misconceptions
    Given Lilymay exists with a target grade and year group
    And she has recorded confidence on "Macbeth Act 1" and a recent misconception on it
    When her learner snapshot is read
    Then the snapshot should report her as a known learner
    And it should include her target grade and year group
    And it should include her per-topic confidence for "Macbeth Act 1"
    And it should include her recent misconception on "Macbeth Act 1"

  # Why: The planner's confidence inputs — one entry per topic carrying its derived band
  @task:TASK-SMP2-01
  @key-example @read-path
  Scenario: Reading per-topic confidences returns one entry per topic carrying its band
    Given Lilymay has resolved confidence of 72 percent on "Macbeth Act 1" and 45 percent on "Metaphor"
    When her per-topic confidences are read
    Then there should be one confidence entry per topic
    And "Macbeth Act 1" should carry the band "secure"
    And "Metaphor" should carry the band "developing"

  # Why: The planner's misconception inputs — recent-window filtered
  @task:TASK-SMP2-02
  @key-example @read-path
  Scenario: Reading recent misconceptions returns those observed within the recency window
    Given Lilymay has a misconception observed 3 days ago and another observed 90 days ago
    When her recent misconceptions are read over the default recency window
    Then only the misconception observed 3 days ago should be returned

  # Why: THE repoint — the planner now reads learner state through the store, not the graph
  @task:TASK-SMP2-05
  @key-example @smoke @planner-repoint
  Scenario: The session planner receives store-backed confidences and misconceptions for a seeded learner
    Given Lilymay has store-recorded confidences and a recent misconception
    When a session is planned for her
    Then the planner should receive her confidences and recent misconceptions
    And the planner should treat her learner state as available

  # Why: Reachable store, learner simply has no records yet — distinct from "store down"
  @task:TASK-SMP2-03
  @key-example @read-path
  Scenario: Reading a learner who has no records yet returns an empty-but-available snapshot
    Given Lilymay exists but has no confidences or misconceptions recorded
    When her learner snapshot is read
    Then the snapshot should report her as a known learner with no confidences and no misconceptions
    And a plan built for her should still treat her learner state as available

  # ==========================================================================
  # GROUP B: Boundary Conditions
  # ==========================================================================

  # Why: Recency-window edge — a misconception exactly at the window edge is included
  @task:TASK-SMP2-02
  @boundary @read-path
  Scenario Outline: Misconceptions are included or excluded at the recency-window edge
    Given Lilymay has a single misconception observed <age> ago
    When her recent misconceptions are read over a 30-day window
    Then the misconception should be <outcome>

    Examples:
      | age     | outcome  |
      | 29 days | returned |
      | 30 days | returned |
      | 31 days | excluded |

  # Why: Band derivation round-trips through the store at every boundary (40/60/80)
  @task:TASK-SMP2-01
  @boundary @read-path
  Scenario Outline: A stored confidence percentage reads back with the boundary-correct band
    Given Lilymay has resolved confidence of <percentage> percent on a topic
    When her per-topic confidences are read
    Then the topic's band should be "<band>"

    Examples:
      | percentage | band       |
      | 39         | struggling |
      | 40         | developing |
      | 59         | developing |
      | 60         | secure     |
      | 79         | secure     |
      | 80         | mastered   |

  # Why: A caller-supplied window narrows the misconception set
  @task:TASK-SMP2-02
  @boundary @read-path
  Scenario: A narrower recency window excludes an otherwise-recent misconception
    Given Lilymay has a misconception observed 10 days ago
    When her recent misconceptions are read over a 7-day window
    Then no misconceptions should be returned

  # Why: Empty-set boundary — zero topics is a valid state, not an error
  @task:TASK-SMP2-01
  @boundary @read-path
  Scenario: Reading confidences for a learner with no topics returns an empty list
    Given Lilymay exists with no recorded confidences
    When her per-topic confidences are read
    Then an empty list should be returned

  # ==========================================================================
  # GROUP C: Negative Cases / Graceful Degradation
  # ==========================================================================

  # Why: Unknown learner is not an error on the read path — returns the empty sentinel
  @task:TASK-SMP2-03
  @negative @read-path
  Scenario: Reading the snapshot for an unknown learner returns the empty snapshot
    Given no learner "ghost" exists in the store
    When the snapshot for "ghost" is read
    Then the snapshot should report that no learner state is available

  # Why: Unknown learner yields empty collections, never an exception
  @task:TASK-SMP2-01
  @negative @read-path
  Scenario: Reading confidences and misconceptions for an unknown learner returns empty results
    Given no learner "ghost" exists in the store
    When the confidences and recent misconceptions for "ghost" are read
    Then both results should be empty

  # Why: Store unreachable must degrade to empty, never propagate — the load-bearing contract
  @task:TASK-SMP2-03
  @negative @edge-case @degradation
  Scenario: When the store is unreachable, the snapshot read degrades to an empty snapshot
    Given the store is unreachable
    When a learner snapshot is read
    Then the snapshot should report that no learner state is available
    And no error should reach the caller

  # Why: Store unreachable → planner takes its unseeded-baseline path
  @task:TASK-SMP2-05
  @negative @edge-case @degradation @planner-repoint
  Scenario: When the store is unreachable, the planner falls back to a baseline plan
    Given the store is unreachable
    When a session is planned for a learner
    Then the planner should treat her learner state as unavailable
    And it should still produce a plan

  # ==========================================================================
  # GROUP D: Edge Cases / Migration Semantics
  # ==========================================================================

  # [ASSUMPTION: confidence=medium] The Postgres store models neither subjects nor texts (the graph denormalised them onto the Student node); the snapshot returns both empty.
  # Why: Documents the intentional post-migration gap
  @task:TASK-SMP2-03
  @edge-case @read-path
  Scenario: The snapshot reports no subjects or current texts because the store does not model them
    Given Lilymay exists with confidences recorded
    When her learner snapshot is read
    Then her subjects and current texts should be empty

  # [ASSUMPTION: confidence=low] band-at-observation is not persisted; it is approximated at read time from the learner's current confidence band for that topic, defaulting to "struggling".
  # Why: The misconception's band-at-observation must be produced despite not being stored
  @task:TASK-SMP2-02
  @edge-case @read-path
  Scenario: A recent misconception is returned with a confidence band at observation
    Given Lilymay has a recent misconception on "Macbeth Act 1"
    When her recent misconceptions are read
    Then the misconception should carry a confidence band at observation

  # [ASSUMPTION: confidence=medium] most_recent_session_id is read from the session table (latest by last activity); the Graphiti-era stale flag is retired.
  # Why: The snapshot's most-recent session reflects the learner's latest recorded session
  @task:TASK-SMP2-03
  @edge-case @read-path
  Scenario: The snapshot reports the learner's most recent session
    Given Lilymay has an earlier and a later recorded session
    When her learner snapshot is read
    Then the snapshot's most recent session should be the later one

  # Why: Timestamps cross the boundary as timezone-aware UTC (ASSUM-011 parity with W1)
  @task:TASK-SMP2-01
  @edge-case @read-path
  Scenario: Learner-state timestamps are returned as timezone-aware UTC
    Given Lilymay has a confidence revised at a known instant
    When her per-topic confidences are read
    Then the revision time should be timezone-aware and expressed in UTC

  # Why: No store wired reads as "no learner state yet", never a crash (provider unset)
  @task:TASK-SMP2-04
  @edge-case @regression @degradation
  Scenario: With no store wired, reads degrade to empty
    Given no store is wired into the runtime
    When a learner snapshot is read
    Then the snapshot should report that no learner state is available

  # Why: After the repoint, planning a session no longer consults the retired graph read path
  @task:TASK-SMP2-06
  @edge-case @regression @planner-repoint
  Scenario: Planning a session no longer consults the retired graph read path
    Given the store holds Lilymay's confidences and recent misconceptions
    When a session is planned for her
    Then her learner state should be sourced entirely from the store
    And the retired graph read path should not be consulted
